/*
 * generated by Xtext
 */
package org.talend.metalanguage.job;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class JobRuntimeModule extends org.talend.metalanguage.job.AbstractJobRuntimeModule {

}
