// ============================================================================
//
// Talend Community Edition
//
// Copyright (C) 2006-2007 Talend - www.talend.com
//
// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License.
//
// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
// Lesser General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
//
// ============================================================================
package org.talend.core.model.genhtml;

/**
 * This class is stored all constants for generating HTML. <br/>
 * 
 */
public interface IHTMLDocConstants {

    public static final String PIC_FOLDER_NAME = "pictures";//$NON-NLS-1$

    public static final String TEMP_FOLDER_NAME = "userHTMLDoc";//$NON-NLS-1$

    public static final String EMPTY_ELEMENT_VALUE = "none";//$NON-NLS-1$

    public static final String TITLE = "Generated by Talend Open Studio. (www.talend.com)";//$NON-NLS-1$

    public static final String TITLE_GEN = "Generated by ";//$NON-NLS-1$

    public static final String VERSION = " VERSION ";//$NON-NLS-1$

    public static final String JOB_PREVIEW_PIC_SUFFIX = ".jpg";//$NON-NLS-1$

    public static final String PICTUREFOLDERPATH = "pictures/";//$NON-NLS-1$

    public static final String TALEND_LOGO_FILE_NAME = "logo.jpg";//$NON-NLS-1$

    public static final String MAIN_XSL_FILE_PATH = "resources/Job.xsl";//$NON-NLS-1$

    public static final String LOGO_FILE_PATH = "icons/logo.jpg";//$NON-NLS-1$

    public static final String WEBSITE_LINK = "http://www.talend.com";//$NON-NLS-1$

    public static final String REPOSITORY = "REPOSITORY"; //$NON-NLS-1$

    public static final String REPOSITORY_BUILT_IN = "BUILT_IN"; //$NON-NLS-1$

    public static final String DISPLAY_BUILT_IN = "Built-In"; //$NON-NLS-1$

    public static final String REPOSITORY_COMMENT = "COMMENT"; //$NON-NLS-1$

    public static final String DISPLAY_COMMENT = "Comment"; //$NON-NLS-1$

    public static final String UNKNOWN = "UNKNOWN"; //$NON-NLS-1$

    public static final String XML_FILE_SUFFIX = ".xml"; //$NON-NLS-1$

    public static final String HTML_FILE_SUFFIX = ".html"; //$NON-NLS-1$

    public static final String TMAP_XSL_FILE_PATH = "resources/tMap.xsl"; //$NON-NLS-1$

    public static final String MAPPERCOMPONENT_XSL_FILE_PATH = "resources/mapperComponent.xsl"; //$NON-NLS-1$

    public static final String TROWGENERATOR_XSL_FILE_PATH = "resources/tRowGenerator.xsl"; //$NON-NLS-1$

    public static final String MAPPER_TABLE_INPUT = "input"; //$NON-NLS-1$

    public static final String MAPPER_TABLE_OUPUT = "output"; //$NON-NLS-1$

    public static final String MAPPER_TABLE_VAR = "var"; //$NON-NLS-1$

    public static final String EXTERNAL_FOLDER_NAME = "externalDoc/"; //$NON-NLS-1$
}
