package org.talend.dataprofiler.persistence;

// Generated Apr 23, 2008 1:33:52 PM by Hibernate Tools 3.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TdqAnalyzedElement generated by hbm2java
 */
public class TdqAnalyzedElement implements java.io.Serializable {

    private Integer eltPk;

    private String eltUuid;

    private String eltConnectionUuid;

    private String eltConnectionName;

    private String eltCatalogName;

    private String eltSchemaName;

    private String eltTableName;

    private String eltColumnName;

    private Date eltBeginDate;

    private Date eltEndDate;

    private int eltVersion;

    private Set<TdqIndicatorValue> tdqIndicatorValues = new HashSet<TdqIndicatorValue>(0);

    public TdqAnalyzedElement() {
    }

    public TdqAnalyzedElement(String eltUuid, String eltConnectionUuid, String eltConnectionName, String eltCatalogName,
            String eltSchemaName, String eltTableName, String eltColumnName, Date eltBeginDate, Date eltEndDate, int eltVersion) {
        this.eltUuid = eltUuid;
        this.eltConnectionUuid = eltConnectionUuid;
        this.eltConnectionName = eltConnectionName;
        this.eltCatalogName = eltCatalogName;
        this.eltSchemaName = eltSchemaName;
        this.eltTableName = eltTableName;
        this.eltColumnName = eltColumnName;
        this.eltBeginDate = eltBeginDate;
        this.eltEndDate = eltEndDate;
        this.eltVersion = eltVersion;
    }

    public TdqAnalyzedElement(String eltUuid, String eltConnectionUuid, String eltConnectionName, String eltCatalogName,
            String eltSchemaName, String eltTableName, String eltColumnName, Date eltBeginDate, Date eltEndDate, int eltVersion,
            Set<TdqIndicatorValue> tdqIndicatorValues) {
        this.eltUuid = eltUuid;
        this.eltConnectionUuid = eltConnectionUuid;
        this.eltConnectionName = eltConnectionName;
        this.eltCatalogName = eltCatalogName;
        this.eltSchemaName = eltSchemaName;
        this.eltTableName = eltTableName;
        this.eltColumnName = eltColumnName;
        this.eltBeginDate = eltBeginDate;
        this.eltEndDate = eltEndDate;
        this.eltVersion = eltVersion;
        this.tdqIndicatorValues = tdqIndicatorValues;
    }

    public Integer getEltPk() {
        return this.eltPk;
    }

    public void setEltPk(Integer eltPk) {
        this.eltPk = eltPk;
    }

    public String getEltUuid() {
        return this.eltUuid;
    }

    public void setEltUuid(String eltUuid) {
        this.eltUuid = eltUuid;
    }

    public String getEltConnectionUuid() {
        return this.eltConnectionUuid;
    }

    public void setEltConnectionUuid(String eltConnectionUuid) {
        this.eltConnectionUuid = eltConnectionUuid;
    }

    public String getEltConnectionName() {
        return this.eltConnectionName;
    }

    public void setEltConnectionName(String eltConnectionName) {
        this.eltConnectionName = eltConnectionName;
    }

    public String getEltCatalogName() {
        return this.eltCatalogName;
    }

    public void setEltCatalogName(String eltCatalogName) {
        this.eltCatalogName = eltCatalogName;
    }

    public String getEltSchemaName() {
        return this.eltSchemaName;
    }

    public void setEltSchemaName(String eltSchemaName) {
        this.eltSchemaName = eltSchemaName;
    }

    public String getEltTableName() {
        return this.eltTableName;
    }

    public void setEltTableName(String eltTableName) {
        this.eltTableName = eltTableName;
    }

    public String getEltColumnName() {
        return this.eltColumnName;
    }

    public void setEltColumnName(String eltColumnName) {
        this.eltColumnName = eltColumnName;
    }

    public Date getEltBeginDate() {
        return this.eltBeginDate;
    }

    public void setEltBeginDate(Date eltBeginDate) {
        this.eltBeginDate = eltBeginDate;
    }

    public Date getEltEndDate() {
        return this.eltEndDate;
    }

    public void setEltEndDate(Date eltEndDate) {
        this.eltEndDate = eltEndDate;
    }

    public int getEltVersion() {
        return this.eltVersion;
    }

    public void setEltVersion(int eltVersion) {
        this.eltVersion = eltVersion;
    }

    public Set<TdqIndicatorValue> getTdqIndicatorValues() {
        return this.tdqIndicatorValues;
    }

    public void setTdqIndicatorValues(Set<TdqIndicatorValue> tdqIndicatorValues) {
        this.tdqIndicatorValues = tdqIndicatorValues;
    }

    public boolean valueEqual(TdqAnalyzedElement analyzedElement) {
        if (!this.eltCatalogName.equals(analyzedElement.getEltCatalogName())) {
            return false;
        } else if (!this.eltColumnName.equals(analyzedElement.eltColumnName)) {
            return false;
        } else if (!this.eltConnectionName.equals(analyzedElement.eltConnectionName)) {
            return false;
        } else if (!this.eltSchemaName.equals(analyzedElement.getEltSchemaName())) {
            return false;
        } else if (!this.eltTableName.equals(analyzedElement.getEltTableName())) {
            return false;
        } else if (!this.eltConnectionUuid.equals(analyzedElement.getEltConnectionUuid())) {
            return false;
        }
        return true;
    }

}
