package org.talend.dataprofiler.persistence;

// Generated Apr 21, 2008 5:00:51 PM by Hibernate Tools 3.2.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TdqDayTime generated by hbm2java
 */
public class TdqDayTime implements java.io.Serializable {

	private int timePk;
	private int timeHour;
	private int timeMinute;
	private Set<TdqIndicatorValue> tdqIndicatorValues = new HashSet<TdqIndicatorValue>(
			0);

	public TdqDayTime() {
	}

	public TdqDayTime(int timePk, int timeHour, int timeMinute) {
		this.timePk = timePk;
		this.timeHour = timeHour;
		this.timeMinute = timeMinute;
	}

	public TdqDayTime(int timePk, int timeHour, int timeMinute,
			Set<TdqIndicatorValue> tdqIndicatorValues) {
		this.timePk = timePk;
		this.timeHour = timeHour;
		this.timeMinute = timeMinute;
		this.tdqIndicatorValues = tdqIndicatorValues;
	}

	public int getTimePk() {
		return this.timePk;
	}

	public void setTimePk(int timePk) {
		this.timePk = timePk;
	}

	public int getTimeHour() {
		return this.timeHour;
	}

	public void setTimeHour(int timeHour) {
		this.timeHour = timeHour;
	}

	public int getTimeMinute() {
		return this.timeMinute;
	}

	public void setTimeMinute(int timeMinute) {
		this.timeMinute = timeMinute;
	}

	public Set<TdqIndicatorValue> getTdqIndicatorValues() {
		return this.tdqIndicatorValues;
	}

	public void setTdqIndicatorValues(Set<TdqIndicatorValue> tdqIndicatorValues) {
		this.tdqIndicatorValues = tdqIndicatorValues;
	}

}
