package org.talend.dataprofiler.persistence;

// Generated Apr 21, 2008 5:00:51 PM by Hibernate Tools 3.2.0.CR1

import java.util.Date;

/**
 * TdqIndicatorValue generated by hbm2java
 */
public class TdqIndicatorValue implements java.io.Serializable {

	private TdqIndicatorValueId id;
	private TdqDayTime tdqDayTime;
	private TdqValues tdqValues;
	private TdqCalendar tdqCalendar;
	private TdqAnalyzedElement tdqAnalyzedElement;
	private TdqAnalysis tdqAnalysis;
	private TdqIndicatorDefinition tdqIndicatorDefinition;
	private Date anExecutionTime;
	private int anDuration;
	private Double indvRealValue;
	private Integer indvIntValue;
	private Integer indvRowCount;
	private char indvRealValueIndicator;

	public TdqIndicatorValue() {
	}

	public TdqIndicatorValue(TdqIndicatorValueId id, TdqDayTime tdqDayTime,
			TdqValues tdqValues, TdqCalendar tdqCalendar,
			TdqAnalyzedElement tdqAnalyzedElement, TdqAnalysis tdqAnalysis,
			TdqIndicatorDefinition tdqIndicatorDefinition,
			Date anExecutionTime, int anDuration, char indvRealValueIndicator) {
		this.id = id;
		this.tdqDayTime = tdqDayTime;
		this.tdqValues = tdqValues;
		this.tdqCalendar = tdqCalendar;
		this.tdqAnalyzedElement = tdqAnalyzedElement;
		this.tdqAnalysis = tdqAnalysis;
		this.tdqIndicatorDefinition = tdqIndicatorDefinition;
		this.anExecutionTime = anExecutionTime;
		this.anDuration = anDuration;
		this.indvRealValueIndicator = indvRealValueIndicator;
	}

	public TdqIndicatorValue(TdqIndicatorValueId id, TdqDayTime tdqDayTime,
			TdqValues tdqValues, TdqCalendar tdqCalendar,
			TdqAnalyzedElement tdqAnalyzedElement, TdqAnalysis tdqAnalysis,
			TdqIndicatorDefinition tdqIndicatorDefinition,
			Date anExecutionTime, int anDuration, Double indvRealValue,
			Integer indvIntValue, Integer indvRowCount,
			char indvRealValueIndicator) {
		this.id = id;
		this.tdqDayTime = tdqDayTime;
		this.tdqValues = tdqValues;
		this.tdqCalendar = tdqCalendar;
		this.tdqAnalyzedElement = tdqAnalyzedElement;
		this.tdqAnalysis = tdqAnalysis;
		this.tdqIndicatorDefinition = tdqIndicatorDefinition;
		this.anExecutionTime = anExecutionTime;
		this.anDuration = anDuration;
		this.indvRealValue = indvRealValue;
		this.indvIntValue = indvIntValue;
		this.indvRowCount = indvRowCount;
		this.indvRealValueIndicator = indvRealValueIndicator;
	}

	public TdqIndicatorValueId getId() {
		return this.id;
	}

	public void setId(TdqIndicatorValueId id) {
		this.id = id;
	}

	public TdqDayTime getTdqDayTime() {
		return this.tdqDayTime;
	}

	public void setTdqDayTime(TdqDayTime tdqDayTime) {
		this.tdqDayTime = tdqDayTime;
	}

	public TdqValues getTdqValues() {
		return this.tdqValues;
	}

	public void setTdqValues(TdqValues tdqValues) {
		this.tdqValues = tdqValues;
	}

	public TdqCalendar getTdqCalendar() {
		return this.tdqCalendar;
	}

	public void setTdqCalendar(TdqCalendar tdqCalendar) {
		this.tdqCalendar = tdqCalendar;
	}

	public TdqAnalyzedElement getTdqAnalyzedElement() {
		return this.tdqAnalyzedElement;
	}

	public void setTdqAnalyzedElement(TdqAnalyzedElement tdqAnalyzedElement) {
		this.tdqAnalyzedElement = tdqAnalyzedElement;
	}

	public TdqAnalysis getTdqAnalysis() {
		return this.tdqAnalysis;
	}

	public void setTdqAnalysis(TdqAnalysis tdqAnalysis) {
		this.tdqAnalysis = tdqAnalysis;
	}

	public TdqIndicatorDefinition getTdqIndicatorDefinition() {
		return this.tdqIndicatorDefinition;
	}

	public void setTdqIndicatorDefinition(
			TdqIndicatorDefinition tdqIndicatorDefinition) {
		this.tdqIndicatorDefinition = tdqIndicatorDefinition;
	}

	public Date getAnExecutionTime() {
		return this.anExecutionTime;
	}

	public void setAnExecutionTime(Date anExecutionTime) {
		this.anExecutionTime = anExecutionTime;
	}

	public int getAnDuration() {
		return this.anDuration;
	}

	public void setAnDuration(int anDuration) {
		this.anDuration = anDuration;
	}

	public Double getIndvRealValue() {
		return this.indvRealValue;
	}

	public void setIndvRealValue(Double indvRealValue) {
		this.indvRealValue = indvRealValue;
	}

	public Integer getIndvIntValue() {
		return this.indvIntValue;
	}

	public void setIndvIntValue(Integer indvIntValue) {
		this.indvIntValue = indvIntValue;
	}

	public Integer getIndvRowCount() {
		return this.indvRowCount;
	}

	public void setIndvRowCount(Integer indvRowCount) {
		this.indvRowCount = indvRowCount;
	}

	public char getIndvRealValueIndicator() {
		return this.indvRealValueIndicator;
	}

	public void setIndvRealValueIndicator(char indvRealValueIndicator) {
		this.indvRealValueIndicator = indvRealValueIndicator;
	}

}
