package org.talend.dataprofiler.persistence;

// Generated Apr 23, 2008 1:33:52 PM by Hibernate Tools 3.2.0.CR1

/**
 * TdqIndicatorValue generated by hbm2java
 */
public class TdqIndicatorValue implements java.io.Serializable {

	private Integer indvPk;
	private TdqDayTime tdqDayTime;
	private TdqAnalyzedElement tdqAnalyzedElement;
	private TdqAnalysis tdqAnalysis;
	private TdqValues tdqValues;
	private TdqIndicatorOptions tdqIndicatorOptions;
	private TdqInterval tdqInterval;
	private TdqIndicatorDefinition tdqIndicatorDefinition;
	private TdqCalendar tdqCalendar;
	private int anDuration;
	private Double indvRealValue;
	private Integer indvIntValue;
	private Integer indvRowCount;
	private char indvValueTypeIndicator;

	public TdqIndicatorValue() {
	}

	public TdqIndicatorValue(TdqDayTime tdqDayTime,
			TdqAnalyzedElement tdqAnalyzedElement, TdqAnalysis tdqAnalysis,
			TdqValues tdqValues, TdqIndicatorOptions tdqIndicatorOptions,
			TdqInterval tdqInterval,
			TdqIndicatorDefinition tdqIndicatorDefinition,
			TdqCalendar tdqCalendar, int anDuration, char indvValueTypeIndicator) {
		this.tdqDayTime = tdqDayTime;
		this.tdqAnalyzedElement = tdqAnalyzedElement;
		this.tdqAnalysis = tdqAnalysis;
		this.tdqValues = tdqValues;
		this.tdqIndicatorOptions = tdqIndicatorOptions;
		this.tdqInterval = tdqInterval;
		this.tdqIndicatorDefinition = tdqIndicatorDefinition;
		this.tdqCalendar = tdqCalendar;
		this.anDuration = anDuration;
		this.indvValueTypeIndicator = indvValueTypeIndicator;
	}

	public TdqIndicatorValue(TdqDayTime tdqDayTime,
			TdqAnalyzedElement tdqAnalyzedElement, TdqAnalysis tdqAnalysis,
			TdqValues tdqValues, TdqIndicatorOptions tdqIndicatorOptions,
			TdqInterval tdqInterval,
			TdqIndicatorDefinition tdqIndicatorDefinition,
			TdqCalendar tdqCalendar, int anDuration, Double indvRealValue,
			Integer indvIntValue, Integer indvRowCount,
			char indvValueTypeIndicator) {
		this.tdqDayTime = tdqDayTime;
		this.tdqAnalyzedElement = tdqAnalyzedElement;
		this.tdqAnalysis = tdqAnalysis;
		this.tdqValues = tdqValues;
		this.tdqIndicatorOptions = tdqIndicatorOptions;
		this.tdqInterval = tdqInterval;
		this.tdqIndicatorDefinition = tdqIndicatorDefinition;
		this.tdqCalendar = tdqCalendar;
		this.anDuration = anDuration;
		this.indvRealValue = indvRealValue;
		this.indvIntValue = indvIntValue;
		this.indvRowCount = indvRowCount;
		this.indvValueTypeIndicator = indvValueTypeIndicator;
	}

	public Integer getIndvPk() {
		return this.indvPk;
	}

	public void setIndvPk(Integer indvPk) {
		this.indvPk = indvPk;
	}

	public TdqDayTime getTdqDayTime() {
		return this.tdqDayTime;
	}

	public void setTdqDayTime(TdqDayTime tdqDayTime) {
		this.tdqDayTime = tdqDayTime;
	}

	public TdqAnalyzedElement getTdqAnalyzedElement() {
		return this.tdqAnalyzedElement;
	}

	public void setTdqAnalyzedElement(TdqAnalyzedElement tdqAnalyzedElement) {
		this.tdqAnalyzedElement = tdqAnalyzedElement;
	}

	public TdqAnalysis getTdqAnalysis() {
		return this.tdqAnalysis;
	}

	public void setTdqAnalysis(TdqAnalysis tdqAnalysis) {
		this.tdqAnalysis = tdqAnalysis;
	}

	public TdqValues getTdqValues() {
		return this.tdqValues;
	}

	public void setTdqValues(TdqValues tdqValues) {
		this.tdqValues = tdqValues;
	}

	public TdqIndicatorOptions getTdqIndicatorOptions() {
		return this.tdqIndicatorOptions;
	}

	public void setTdqIndicatorOptions(TdqIndicatorOptions tdqIndicatorOptions) {
		this.tdqIndicatorOptions = tdqIndicatorOptions;
	}

	public TdqInterval getTdqInterval() {
		return this.tdqInterval;
	}

	public void setTdqInterval(TdqInterval tdqInterval) {
		this.tdqInterval = tdqInterval;
	}

	public TdqIndicatorDefinition getTdqIndicatorDefinition() {
		return this.tdqIndicatorDefinition;
	}

	public void setTdqIndicatorDefinition(
			TdqIndicatorDefinition tdqIndicatorDefinition) {
		this.tdqIndicatorDefinition = tdqIndicatorDefinition;
	}

	public TdqCalendar getTdqCalendar() {
		return this.tdqCalendar;
	}

	public void setTdqCalendar(TdqCalendar tdqCalendar) {
		this.tdqCalendar = tdqCalendar;
	}

	public int getAnDuration() {
		return this.anDuration;
	}

	public void setAnDuration(int anDuration) {
		this.anDuration = anDuration;
	}

	public Double getIndvRealValue() {
		return this.indvRealValue;
	}

	public void setIndvRealValue(Double indvRealValue) {
		this.indvRealValue = indvRealValue;
	}

	public Integer getIndvIntValue() {
		return this.indvIntValue;
	}

	public void setIndvIntValue(Integer indvIntValue) {
		this.indvIntValue = indvIntValue;
	}

	public Integer getIndvRowCount() {
		return this.indvRowCount;
	}

	public void setIndvRowCount(Integer indvRowCount) {
		this.indvRowCount = indvRowCount;
	}

	public char getIndvValueTypeIndicator() {
		return this.indvValueTypeIndicator;
	}

	public void setIndvValueTypeIndicator(char indvValueTypeIndicator) {
		this.indvValueTypeIndicator = indvValueTypeIndicator;
	}

}
