package org.talend.dataprofiler.persistence;

// Generated Apr 23, 2008 1:33:52 PM by Hibernate Tools 3.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TdqIndicatorDefinition generated by hbm2java
 */
public class TdqIndicatorDefinition implements java.io.Serializable {

	private Integer indPk;
	private String indLabel;
	private String indType;
	private String indCategory;
	private String indSubcategory;
	private Date indBeginDate;
	private Date indEndDate;
	private int indVersion;
	private Set<TdqIndicatorValue> tdqIndicatorValues = new HashSet<TdqIndicatorValue>(
			0);

	public TdqIndicatorDefinition() {
	}

	public TdqIndicatorDefinition(String indLabel, String indType,
			String indCategory, String indSubcategory, Date indBeginDate,
			Date indEndDate, int indVersion) {
		this.indLabel = indLabel;
		this.indType = indType;
		this.indCategory = indCategory;
		this.indSubcategory = indSubcategory;
		this.indBeginDate = indBeginDate;
		this.indEndDate = indEndDate;
		this.indVersion = indVersion;
	}

	public TdqIndicatorDefinition(String indLabel, String indType,
			String indCategory, String indSubcategory, Date indBeginDate,
			Date indEndDate, int indVersion,
			Set<TdqIndicatorValue> tdqIndicatorValues) {
		this.indLabel = indLabel;
		this.indType = indType;
		this.indCategory = indCategory;
		this.indSubcategory = indSubcategory;
		this.indBeginDate = indBeginDate;
		this.indEndDate = indEndDate;
		this.indVersion = indVersion;
		this.tdqIndicatorValues = tdqIndicatorValues;
	}

	public Integer getIndPk() {
		return this.indPk;
	}

	public void setIndPk(Integer indPk) {
		this.indPk = indPk;
	}

	public String getIndLabel() {
		return this.indLabel;
	}

	public void setIndLabel(String indLabel) {
		this.indLabel = indLabel;
	}

	public String getIndType() {
		return this.indType;
	}

	public void setIndType(String indType) {
		this.indType = indType;
	}

	public String getIndCategory() {
		return this.indCategory;
	}

	public void setIndCategory(String indCategory) {
		this.indCategory = indCategory;
	}

	public String getIndSubcategory() {
		return this.indSubcategory;
	}

	public void setIndSubcategory(String indSubcategory) {
		this.indSubcategory = indSubcategory;
	}

	public Date getIndBeginDate() {
		return this.indBeginDate;
	}

	public void setIndBeginDate(Date indBeginDate) {
		this.indBeginDate = indBeginDate;
	}

	public Date getIndEndDate() {
		return this.indEndDate;
	}

	public void setIndEndDate(Date indEndDate) {
		this.indEndDate = indEndDate;
	}

	public int getIndVersion() {
		return this.indVersion;
	}

	public void setIndVersion(int indVersion) {
		this.indVersion = indVersion;
	}

	public Set<TdqIndicatorValue> getTdqIndicatorValues() {
		return this.tdqIndicatorValues;
	}

	public void setTdqIndicatorValues(Set<TdqIndicatorValue> tdqIndicatorValues) {
		this.tdqIndicatorValues = tdqIndicatorValues;
	}

}
