package org.talend.dataprofiler.persistence;

// Generated Apr 23, 2008 1:33:52 PM by Hibernate Tools 3.2.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TdqIndicatorOptions generated by hbm2java
 */
public class TdqIndicatorOptions implements java.io.Serializable {

	private Integer inoPk;
	private char inoCaseSensitive;
	private String inoRegexp;
	private char inoCountNulls;
	private int inoCountBlanks;
	private Set<TdqIndicatorValue> tdqIndicatorValues = new HashSet<TdqIndicatorValue>(
			0);

	public TdqIndicatorOptions() {
	}

	public TdqIndicatorOptions(char inoCaseSensitive, String inoRegexp,
			char inoCountNulls, int inoCountBlanks) {
		this.inoCaseSensitive = inoCaseSensitive;
		this.inoRegexp = inoRegexp;
		this.inoCountNulls = inoCountNulls;
		this.inoCountBlanks = inoCountBlanks;
	}

	public TdqIndicatorOptions(char inoCaseSensitive, String inoRegexp,
			char inoCountNulls, int inoCountBlanks,
			Set<TdqIndicatorValue> tdqIndicatorValues) {
		this.inoCaseSensitive = inoCaseSensitive;
		this.inoRegexp = inoRegexp;
		this.inoCountNulls = inoCountNulls;
		this.inoCountBlanks = inoCountBlanks;
		this.tdqIndicatorValues = tdqIndicatorValues;
	}

	public Integer getInoPk() {
		return this.inoPk;
	}

	public void setInoPk(Integer inoPk) {
		this.inoPk = inoPk;
	}

	public char getInoCaseSensitive() {
		return this.inoCaseSensitive;
	}

	public void setInoCaseSensitive(char inoCaseSensitive) {
		this.inoCaseSensitive = inoCaseSensitive;
	}

	public String getInoRegexp() {
		return this.inoRegexp;
	}

	public void setInoRegexp(String inoRegexp) {
		this.inoRegexp = inoRegexp;
	}

	public char getInoCountNulls() {
		return this.inoCountNulls;
	}

	public void setInoCountNulls(char inoCountNulls) {
		this.inoCountNulls = inoCountNulls;
	}

	public int getInoCountBlanks() {
		return this.inoCountBlanks;
	}

	public void setInoCountBlanks(int inoCountBlanks) {
		this.inoCountBlanks = inoCountBlanks;
	}

	public Set<TdqIndicatorValue> getTdqIndicatorValues() {
		return this.tdqIndicatorValues;
	}

	public void setTdqIndicatorValues(Set<TdqIndicatorValue> tdqIndicatorValues) {
		this.tdqIndicatorValues = tdqIndicatorValues;
	}

}
