package org.talend.dataprofiler.persistence;

// Generated Apr 21, 2008 5:00:51 PM by Hibernate Tools 3.2.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TdqValues generated by hbm2java
 */
public class TdqValues implements java.io.Serializable {

	private int valPk;
	private String valString;
	private Set<TdqIndicatorValue> tdqIndicatorValues = new HashSet<TdqIndicatorValue>(
			0);

	public TdqValues() {
	}

	public TdqValues(int valPk, String valString) {
		this.valPk = valPk;
		this.valString = valString;
	}

	public TdqValues(int valPk, String valString,
			Set<TdqIndicatorValue> tdqIndicatorValues) {
		this.valPk = valPk;
		this.valString = valString;
		this.tdqIndicatorValues = tdqIndicatorValues;
	}

	public int getValPk() {
		return this.valPk;
	}

	public void setValPk(int valPk) {
		this.valPk = valPk;
	}

	public String getValString() {
		return this.valString;
	}

	public void setValString(String valString) {
		this.valString = valString;
	}

	public Set<TdqIndicatorValue> getTdqIndicatorValues() {
		return this.tdqIndicatorValues;
	}

	public void setTdqIndicatorValues(Set<TdqIndicatorValue> tdqIndicatorValues) {
		this.tdqIndicatorValues = tdqIndicatorValues;
	}

}
