/*
* generated by Xtext
*/
package org.talend.metalanguage.job.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.talend.metalanguage.job.services.JobGrammarAccess;

public class JobParser extends AbstractContentAssistParser {
	
	@Inject
	private JobGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.talend.metalanguage.job.ui.contentassist.antlr.internal.InternalJobParser createParser() {
		org.talend.metalanguage.job.ui.contentassist.antlr.internal.InternalJobParser result = new org.talend.metalanguage.job.ui.contentassist.antlr.internal.InternalJobParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getExternalDataAccess().getAlternatives(), "rule__ExternalData__Alternatives");
					put(grammarAccess.getDBInputTableAccess().getAlternatives_6_1(), "rule__DBInputTable__Alternatives_6_1");
					put(grammarAccess.getInputTableAccess().getAlternatives_4_1(), "rule__InputTable__Alternatives_4_1");
					put(grammarAccess.getVarTableAccess().getAlternatives_4_1(), "rule__VarTable__Alternatives_4_1");
					put(grammarAccess.getOutputTableAccess().getAlternatives_4_1(), "rule__OutputTable__Alternatives_4_1");
					put(grammarAccess.getNodeTypeAccess().getElementParameterAlternatives_11_0(), "rule__NodeType__ElementParameterAlternatives_11_0");
					put(grammarAccess.getNodeTypeAccess().getElementParameterAlternatives_12_1_0(), "rule__NodeType__ElementParameterAlternatives_12_1_0");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
					put(grammarAccess.getProcessTypeAccess().getGroup(), "rule__ProcessType__Group__0");
					put(grammarAccess.getProcessTypeAccess().getGroup_1(), "rule__ProcessType__Group_1__0");
					put(grammarAccess.getParametersTypeAccess().getGroup(), "rule__ParametersType__Group__0");
					put(grammarAccess.getParametersTypeAccess().getGroup_1(), "rule__ParametersType__Group_1__0");
					put(grammarAccess.getDBMapperDataAccess().getGroup(), "rule__DBMapperData__Group__0");
					put(grammarAccess.getDBMapperDataAccess().getGroup_3(), "rule__DBMapperData__Group_3__0");
					put(grammarAccess.getDBMapperDataAccess().getGroup_4(), "rule__DBMapperData__Group_4__0");
					put(grammarAccess.getDBMapperDataAccess().getGroup_5(), "rule__DBMapperData__Group_5__0");
					put(grammarAccess.getDBInputTableAccess().getGroup(), "rule__DBInputTable__Group__0");
					put(grammarAccess.getDBInputTableAccess().getGroup_3(), "rule__DBInputTable__Group_3__0");
					put(grammarAccess.getDBInputTableAccess().getGroup_4(), "rule__DBInputTable__Group_4__0");
					put(grammarAccess.getDBInputTableAccess().getGroup_5(), "rule__DBInputTable__Group_5__0");
					put(grammarAccess.getDBInputTableAccess().getGroup_6(), "rule__DBInputTable__Group_6__0");
					put(grammarAccess.getDBInputTableAccess().getGroup_7(), "rule__DBInputTable__Group_7__0");
					put(grammarAccess.getDBVarTableAccess().getGroup(), "rule__DBVarTable__Group__0");
					put(grammarAccess.getDBVarTableAccess().getGroup_3(), "rule__DBVarTable__Group_3__0");
					put(grammarAccess.getDBVarTableAccess().getGroup_4(), "rule__DBVarTable__Group_4__0");
					put(grammarAccess.getDBOutputTableAccess().getGroup(), "rule__DBOutputTable__Group__0");
					put(grammarAccess.getDBOutputTableAccess().getGroup_3(), "rule__DBOutputTable__Group_3__0");
					put(grammarAccess.getDBOutputTableAccess().getGroup_4(), "rule__DBOutputTable__Group_4__0");
					put(grammarAccess.getDBMapperTableEntryAccess().getGroup(), "rule__DBMapperTableEntry__Group__0");
					put(grammarAccess.getDBMapperTableEntryAccess().getGroup_5(), "rule__DBMapperTableEntry__Group_5__0");
					put(grammarAccess.getDBMapperTableEntryAccess().getGroup_6(), "rule__DBMapperTableEntry__Group_6__0");
					put(grammarAccess.getDBMapperTableEntryAccess().getGroup_7(), "rule__DBMapperTableEntry__Group_7__0");
					put(grammarAccess.getDBMapperTableEntryAccess().getGroup_8(), "rule__DBMapperTableEntry__Group_8__0");
					put(grammarAccess.getDBMapperTableEntryAccess().getGroup_9(), "rule__DBMapperTableEntry__Group_9__0");
					put(grammarAccess.getDBFilterEntryAccess().getGroup(), "rule__DBFilterEntry__Group__0");
					put(grammarAccess.getMapperDataAccess().getGroup(), "rule__MapperData__Group__0");
					put(grammarAccess.getMapperDataAccess().getGroup_3(), "rule__MapperData__Group_3__0");
					put(grammarAccess.getMapperDataAccess().getGroup_4(), "rule__MapperData__Group_4__0");
					put(grammarAccess.getMapperDataAccess().getGroup_5(), "rule__MapperData__Group_5__0");
					put(grammarAccess.getMapperDataAccess().getGroup_6(), "rule__MapperData__Group_6__0");
					put(grammarAccess.getUiPropertiesAccess().getGroup(), "rule__UiProperties__Group__0");
					put(grammarAccess.getInputTableAccess().getGroup(), "rule__InputTable__Group__0");
					put(grammarAccess.getInputTableAccess().getGroup_3(), "rule__InputTable__Group_3__0");
					put(grammarAccess.getInputTableAccess().getGroup_4(), "rule__InputTable__Group_4__0");
					put(grammarAccess.getInputTableAccess().getGroup_5(), "rule__InputTable__Group_5__0");
					put(grammarAccess.getInputTableAccess().getGroup_6(), "rule__InputTable__Group_6__0");
					put(grammarAccess.getInputTableAccess().getGroup_7(), "rule__InputTable__Group_7__0");
					put(grammarAccess.getInputTableAccess().getGroup_8(), "rule__InputTable__Group_8__0");
					put(grammarAccess.getInputTableAccess().getGroup_9(), "rule__InputTable__Group_9__0");
					put(grammarAccess.getVarTableAccess().getGroup(), "rule__VarTable__Group__0");
					put(grammarAccess.getVarTableAccess().getGroup_3(), "rule__VarTable__Group_3__0");
					put(grammarAccess.getVarTableAccess().getGroup_4(), "rule__VarTable__Group_4__0");
					put(grammarAccess.getOutputTableAccess().getGroup(), "rule__OutputTable__Group__0");
					put(grammarAccess.getOutputTableAccess().getGroup_3(), "rule__OutputTable__Group_3__0");
					put(grammarAccess.getOutputTableAccess().getGroup_4(), "rule__OutputTable__Group_4__0");
					put(grammarAccess.getOutputTableAccess().getGroup_5(), "rule__OutputTable__Group_5__0");
					put(grammarAccess.getOutputTableAccess().getGroup_6(), "rule__OutputTable__Group_6__0");
					put(grammarAccess.getOutputTableAccess().getGroup_7(), "rule__OutputTable__Group_7__0");
					put(grammarAccess.getOutputTableAccess().getGroup_8(), "rule__OutputTable__Group_8__0");
					put(grammarAccess.getOutputTableAccess().getGroup_9(), "rule__OutputTable__Group_9__0");
					put(grammarAccess.getOutputTableAccess().getGroup_10(), "rule__OutputTable__Group_10__0");
					put(grammarAccess.getOutputTableAccess().getGroup_11(), "rule__OutputTable__Group_11__0");
					put(grammarAccess.getMapperTableEntryAccess().getGroup(), "rule__MapperTableEntry__Group__0");
					put(grammarAccess.getMapperTableEntryAccess().getGroup_5(), "rule__MapperTableEntry__Group_5__0");
					put(grammarAccess.getMapperTableEntryAccess().getGroup_6(), "rule__MapperTableEntry__Group_6__0");
					put(grammarAccess.getMapperTableEntryAccess().getGroup_7(), "rule__MapperTableEntry__Group_7__0");
					put(grammarAccess.getNodeTypeAccess().getGroup(), "rule__NodeType__Group__0");
					put(grammarAccess.getNodeTypeAccess().getGroup_4(), "rule__NodeType__Group_4__0");
					put(grammarAccess.getNodeTypeAccess().getGroup_5(), "rule__NodeType__Group_5__0");
					put(grammarAccess.getNodeTypeAccess().getGroup_6(), "rule__NodeType__Group_6__0");
					put(grammarAccess.getNodeTypeAccess().getGroup_6_1(), "rule__NodeType__Group_6_1__0");
					put(grammarAccess.getNodeTypeAccess().getGroup_12(), "rule__NodeType__Group_12__0");
					put(grammarAccess.getContextTypeAccess().getGroup(), "rule__ContextType__Group__0");
					put(grammarAccess.getContextTypeAccess().getGroup_3(), "rule__ContextType__Group_3__0");
					put(grammarAccess.getContextTypeAccess().getGroup_4(), "rule__ContextType__Group_4__0");
					put(grammarAccess.getContextTypeAccess().getGroup_5(), "rule__ContextType__Group_5__0");
					put(grammarAccess.getContextTypeAccess().getGroup_5_1(), "rule__ContextType__Group_5_1__0");
					put(grammarAccess.getContextParameterTypeAccess().getGroup(), "rule__ContextParameterType__Group__0");
					put(grammarAccess.getContextParameterTypeAccess().getGroup_3(), "rule__ContextParameterType__Group_3__0");
					put(grammarAccess.getContextParameterTypeAccess().getGroup_4(), "rule__ContextParameterType__Group_4__0");
					put(grammarAccess.getContextParameterTypeAccess().getGroup_5(), "rule__ContextParameterType__Group_5__0");
					put(grammarAccess.getContextParameterTypeAccess().getGroup_6(), "rule__ContextParameterType__Group_6__0");
					put(grammarAccess.getContextParameterTypeAccess().getGroup_7(), "rule__ContextParameterType__Group_7__0");
					put(grammarAccess.getContextParameterTypeAccess().getGroup_8(), "rule__ContextParameterType__Group_8__0");
					put(grammarAccess.getContextParameterTypeAccess().getGroup_9(), "rule__ContextParameterType__Group_9__0");
					put(grammarAccess.getConnectionTypeAccess().getGroup(), "rule__ConnectionType__Group__0");
					put(grammarAccess.getConnectionTypeAccess().getGroup_3(), "rule__ConnectionType__Group_3__0");
					put(grammarAccess.getConnectionTypeAccess().getGroup_4(), "rule__ConnectionType__Group_4__0");
					put(grammarAccess.getConnectionTypeAccess().getGroup_5(), "rule__ConnectionType__Group_5__0");
					put(grammarAccess.getConnectionTypeAccess().getGroup_6(), "rule__ConnectionType__Group_6__0");
					put(grammarAccess.getConnectionTypeAccess().getGroup_7(), "rule__ConnectionType__Group_7__0");
					put(grammarAccess.getConnectionTypeAccess().getGroup_8(), "rule__ConnectionType__Group_8__0");
					put(grammarAccess.getConnectionTypeAccess().getGroup_9(), "rule__ConnectionType__Group_9__0");
					put(grammarAccess.getConnectionTypeAccess().getGroup_10(), "rule__ConnectionType__Group_10__0");
					put(grammarAccess.getConnectionTypeAccess().getGroup_11(), "rule__ConnectionType__Group_11__0");
					put(grammarAccess.getNoteTypeAccess().getGroup(), "rule__NoteType__Group__0");
					put(grammarAccess.getNoteTypeAccess().getGroup_2(), "rule__NoteType__Group_2__0");
					put(grammarAccess.getNoteTypeAccess().getGroup_3(), "rule__NoteType__Group_3__0");
					put(grammarAccess.getNoteTypeAccess().getGroup_4(), "rule__NoteType__Group_4__0");
					put(grammarAccess.getNoteTypeAccess().getGroup_6(), "rule__NoteType__Group_6__0");
					put(grammarAccess.getElementParameterTypeAccess().getGroup(), "rule__ElementParameterType__Group__0");
					put(grammarAccess.getElementParameterTypeAccess().getGroup_1(), "rule__ElementParameterType__Group_1__0");
					put(grammarAccess.getSchemaElementParameterTypeAccess().getGroup(), "rule__SchemaElementParameterType__Group__0");
					put(grammarAccess.getSchemaElementParameterTypeAccess().getGroup_1(), "rule__SchemaElementParameterType__Group_1__0");
					put(grammarAccess.getSchemaElementParameterTypeAccess().getGroup_1_3(), "rule__SchemaElementParameterType__Group_1_3__0");
					put(grammarAccess.getElementValueTypeAccess().getGroup(), "rule__ElementValueType__Group__0");
					put(grammarAccess.getElementValueTypeAccess().getGroup_1(), "rule__ElementValueType__Group_1__0");
					put(grammarAccess.getElementValueTypeAccess().getGroup_2(), "rule__ElementValueType__Group_2__0");
					put(grammarAccess.getElementValueTypeAccess().getGroup_3(), "rule__ElementValueType__Group_3__0");
					put(grammarAccess.getMetadataTypeAccess().getGroup(), "rule__MetadataType__Group__0");
					put(grammarAccess.getMetadataTypeAccess().getGroup_3(), "rule__MetadataType__Group_3__0");
					put(grammarAccess.getMetadataTypeAccess().getGroup_4(), "rule__MetadataType__Group_4__0");
					put(grammarAccess.getMetadataTypeAccess().getGroup_5(), "rule__MetadataType__Group_5__0");
					put(grammarAccess.getMetadataTypeAccess().getGroup_6(), "rule__MetadataType__Group_6__0");
					put(grammarAccess.getMetadataTypeAccess().getGroup_7(), "rule__MetadataType__Group_7__0");
					put(grammarAccess.getColumnTypeAccess().getGroup(), "rule__ColumnType__Group__0");
					put(grammarAccess.getColumnTypeAccess().getGroup_3(), "rule__ColumnType__Group_3__0");
					put(grammarAccess.getColumnTypeAccess().getGroup_4(), "rule__ColumnType__Group_4__0");
					put(grammarAccess.getColumnTypeAccess().getGroup_5(), "rule__ColumnType__Group_5__0");
					put(grammarAccess.getColumnTypeAccess().getGroup_6(), "rule__ColumnType__Group_6__0");
					put(grammarAccess.getColumnTypeAccess().getGroup_7(), "rule__ColumnType__Group_7__0");
					put(grammarAccess.getColumnTypeAccess().getGroup_8(), "rule__ColumnType__Group_8__0");
					put(grammarAccess.getColumnTypeAccess().getGroup_9(), "rule__ColumnType__Group_9__0");
					put(grammarAccess.getColumnTypeAccess().getGroup_10(), "rule__ColumnType__Group_10__0");
					put(grammarAccess.getColumnTypeAccess().getGroup_11(), "rule__ColumnType__Group_11__0");
					put(grammarAccess.getColumnTypeAccess().getGroup_12(), "rule__ColumnType__Group_12__0");
					put(grammarAccess.getColumnTypeAccess().getGroup_13(), "rule__ColumnType__Group_13__0");
					put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
					put(grammarAccess.getProcessTypeAccess().getParametersAssignment_1_2(), "rule__ProcessType__ParametersAssignment_1_2");
					put(grammarAccess.getProcessTypeAccess().getNodeAssignment_2(), "rule__ProcessType__NodeAssignment_2");
					put(grammarAccess.getProcessTypeAccess().getConnectionAssignment_3(), "rule__ProcessType__ConnectionAssignment_3");
					put(grammarAccess.getProcessTypeAccess().getNoteAssignment_4(), "rule__ProcessType__NoteAssignment_4");
					put(grammarAccess.getProcessTypeAccess().getContextAssignment_5(), "rule__ProcessType__ContextAssignment_5");
					put(grammarAccess.getParametersTypeAccess().getElementParameterAssignment_0(), "rule__ParametersType__ElementParameterAssignment_0");
					put(grammarAccess.getParametersTypeAccess().getElementParameterAssignment_1_1(), "rule__ParametersType__ElementParameterAssignment_1_1");
					put(grammarAccess.getDBMapperDataAccess().getInputTablesAssignment_3_2(), "rule__DBMapperData__InputTablesAssignment_3_2");
					put(grammarAccess.getDBMapperDataAccess().getVarTablesAssignment_4_2(), "rule__DBMapperData__VarTablesAssignment_4_2");
					put(grammarAccess.getDBMapperDataAccess().getOutputTablesAssignment_5_2(), "rule__DBMapperData__OutputTablesAssignment_5_2");
					put(grammarAccess.getDBInputTableAccess().getNameAssignment_2(), "rule__DBInputTable__NameAssignment_2");
					put(grammarAccess.getDBInputTableAccess().getMinimizedAssignment_3_1(), "rule__DBInputTable__MinimizedAssignment_3_1");
					put(grammarAccess.getDBInputTableAccess().getReadonlyAssignment_4_1(), "rule__DBInputTable__ReadonlyAssignment_4_1");
					put(grammarAccess.getDBInputTableAccess().getTableNameAssignment_5_1(), "rule__DBInputTable__TableNameAssignment_5_1");
					put(grammarAccess.getDBInputTableAccess().getJoinTypeAssignment_6_1_0(), "rule__DBInputTable__JoinTypeAssignment_6_1_0");
					put(grammarAccess.getDBInputTableAccess().getJoinTypeAssignment_6_1_1(), "rule__DBInputTable__JoinTypeAssignment_6_1_1");
					put(grammarAccess.getDBInputTableAccess().getJoinTypeAssignment_6_1_2(), "rule__DBInputTable__JoinTypeAssignment_6_1_2");
					put(grammarAccess.getDBInputTableAccess().getJoinTypeAssignment_6_1_3(), "rule__DBInputTable__JoinTypeAssignment_6_1_3");
					put(grammarAccess.getDBInputTableAccess().getJoinTypeAssignment_6_1_4(), "rule__DBInputTable__JoinTypeAssignment_6_1_4");
					put(grammarAccess.getDBInputTableAccess().getJoinTypeAssignment_6_1_5(), "rule__DBInputTable__JoinTypeAssignment_6_1_5");
					put(grammarAccess.getDBInputTableAccess().getJoinTypeAssignment_6_1_6(), "rule__DBInputTable__JoinTypeAssignment_6_1_6");
					put(grammarAccess.getDBInputTableAccess().getJoinTypeAssignment_6_1_7(), "rule__DBInputTable__JoinTypeAssignment_6_1_7");
					put(grammarAccess.getDBInputTableAccess().getAliasAssignment_7_1(), "rule__DBInputTable__AliasAssignment_7_1");
					put(grammarAccess.getDBInputTableAccess().getDBMapperTableEntriesAssignment_8(), "rule__DBInputTable__DBMapperTableEntriesAssignment_8");
					put(grammarAccess.getDBVarTableAccess().getNameAssignment_2(), "rule__DBVarTable__NameAssignment_2");
					put(grammarAccess.getDBVarTableAccess().getMinimizedAssignment_3_1(), "rule__DBVarTable__MinimizedAssignment_3_1");
					put(grammarAccess.getDBVarTableAccess().getReadonlyAssignment_4_1(), "rule__DBVarTable__ReadonlyAssignment_4_1");
					put(grammarAccess.getDBVarTableAccess().getDBMapperTableEntriesAssignment_5(), "rule__DBVarTable__DBMapperTableEntriesAssignment_5");
					put(grammarAccess.getDBOutputTableAccess().getNameAssignment_2(), "rule__DBOutputTable__NameAssignment_2");
					put(grammarAccess.getDBOutputTableAccess().getMinimizedAssignment_3_1(), "rule__DBOutputTable__MinimizedAssignment_3_1");
					put(grammarAccess.getDBOutputTableAccess().getReadonlyAssignment_4_1(), "rule__DBOutputTable__ReadonlyAssignment_4_1");
					put(grammarAccess.getDBOutputTableAccess().getDBMapperTableEntriesAssignment_5(), "rule__DBOutputTable__DBMapperTableEntriesAssignment_5");
					put(grammarAccess.getDBOutputTableAccess().getFilterEntriesAssignment_6(), "rule__DBOutputTable__FilterEntriesAssignment_6");
					put(grammarAccess.getDBMapperTableEntryAccess().getNameAssignment_4(), "rule__DBMapperTableEntry__NameAssignment_4");
					put(grammarAccess.getDBMapperTableEntryAccess().getTypeAssignment_5_2(), "rule__DBMapperTableEntry__TypeAssignment_5_2");
					put(grammarAccess.getDBMapperTableEntryAccess().getNullableAssignment_6_2(), "rule__DBMapperTableEntry__NullableAssignment_6_2");
					put(grammarAccess.getDBMapperTableEntryAccess().getExpressionAssignment_7_2(), "rule__DBMapperTableEntry__ExpressionAssignment_7_2");
					put(grammarAccess.getDBMapperTableEntryAccess().getJoinAssignment_8_2(), "rule__DBMapperTableEntry__JoinAssignment_8_2");
					put(grammarAccess.getDBMapperTableEntryAccess().getOperatorAssignment_9_2(), "rule__DBMapperTableEntry__OperatorAssignment_9_2");
					put(grammarAccess.getDBFilterEntryAccess().getNameAssignment_3(), "rule__DBFilterEntry__NameAssignment_3");
					put(grammarAccess.getDBFilterEntryAccess().getExpressionAssignment_6(), "rule__DBFilterEntry__ExpressionAssignment_6");
					put(grammarAccess.getMapperDataAccess().getUiPropertiesAssignment_3_2(), "rule__MapperData__UiPropertiesAssignment_3_2");
					put(grammarAccess.getMapperDataAccess().getInputTablesAssignment_4_2(), "rule__MapperData__InputTablesAssignment_4_2");
					put(grammarAccess.getMapperDataAccess().getVarTablesAssignment_5_2(), "rule__MapperData__VarTablesAssignment_5_2");
					put(grammarAccess.getMapperDataAccess().getOutputTablesAssignment_6_2(), "rule__MapperData__OutputTablesAssignment_6_2");
					put(grammarAccess.getUiPropertiesAccess().getShellMaximizedAssignment_2(), "rule__UiProperties__ShellMaximizedAssignment_2");
					put(grammarAccess.getInputTableAccess().getNameAssignment_2(), "rule__InputTable__NameAssignment_2");
					put(grammarAccess.getInputTableAccess().getMinimizedAssignment_3_1(), "rule__InputTable__MinimizedAssignment_3_1");
					put(grammarAccess.getInputTableAccess().getSizeStateAssignment_4_1_0(), "rule__InputTable__SizeStateAssignment_4_1_0");
					put(grammarAccess.getInputTableAccess().getSizeStateAssignment_4_1_1(), "rule__InputTable__SizeStateAssignment_4_1_1");
					put(grammarAccess.getInputTableAccess().getSizeStateAssignment_4_1_2(), "rule__InputTable__SizeStateAssignment_4_1_2");
					put(grammarAccess.getInputTableAccess().getExpressionFilterAssignment_5_1(), "rule__InputTable__ExpressionFilterAssignment_5_1");
					put(grammarAccess.getInputTableAccess().getActivateExpressionFilterAssignment_6_1(), "rule__InputTable__ActivateExpressionFilterAssignment_6_1");
					put(grammarAccess.getInputTableAccess().getActivateCondensedToolAssignment_7_1(), "rule__InputTable__ActivateCondensedToolAssignment_7_1");
					put(grammarAccess.getInputTableAccess().getMatchingModeAssignment_8_1(), "rule__InputTable__MatchingModeAssignment_8_1");
					put(grammarAccess.getInputTableAccess().getLookupModeAssignment_9_1(), "rule__InputTable__LookupModeAssignment_9_1");
					put(grammarAccess.getInputTableAccess().getMapperTableEntriesAssignment_10(), "rule__InputTable__MapperTableEntriesAssignment_10");
					put(grammarAccess.getVarTableAccess().getNameAssignment_2(), "rule__VarTable__NameAssignment_2");
					put(grammarAccess.getVarTableAccess().getMinimizedAssignment_3_1(), "rule__VarTable__MinimizedAssignment_3_1");
					put(grammarAccess.getVarTableAccess().getSizeStateAssignment_4_1_0(), "rule__VarTable__SizeStateAssignment_4_1_0");
					put(grammarAccess.getVarTableAccess().getSizeStateAssignment_4_1_1(), "rule__VarTable__SizeStateAssignment_4_1_1");
					put(grammarAccess.getVarTableAccess().getSizeStateAssignment_4_1_2(), "rule__VarTable__SizeStateAssignment_4_1_2");
					put(grammarAccess.getVarTableAccess().getMapperTableEntriesAssignment_5(), "rule__VarTable__MapperTableEntriesAssignment_5");
					put(grammarAccess.getOutputTableAccess().getNameAssignment_2(), "rule__OutputTable__NameAssignment_2");
					put(grammarAccess.getOutputTableAccess().getMinimizedAssignment_3_1(), "rule__OutputTable__MinimizedAssignment_3_1");
					put(grammarAccess.getOutputTableAccess().getSizeStateAssignment_4_1_0(), "rule__OutputTable__SizeStateAssignment_4_1_0");
					put(grammarAccess.getOutputTableAccess().getSizeStateAssignment_4_1_1(), "rule__OutputTable__SizeStateAssignment_4_1_1");
					put(grammarAccess.getOutputTableAccess().getSizeStateAssignment_4_1_2(), "rule__OutputTable__SizeStateAssignment_4_1_2");
					put(grammarAccess.getOutputTableAccess().getExpressionFilterAssignment_5_1(), "rule__OutputTable__ExpressionFilterAssignment_5_1");
					put(grammarAccess.getOutputTableAccess().getActivateExpressionFilterAssignment_6_1(), "rule__OutputTable__ActivateExpressionFilterAssignment_6_1");
					put(grammarAccess.getOutputTableAccess().getActivateCondensedToolAssignment_7_1(), "rule__OutputTable__ActivateCondensedToolAssignment_7_1");
					put(grammarAccess.getOutputTableAccess().getRejectAssignment_8_1(), "rule__OutputTable__RejectAssignment_8_1");
					put(grammarAccess.getOutputTableAccess().getRejectInnerJoinAssignment_9_1(), "rule__OutputTable__RejectInnerJoinAssignment_9_1");
					put(grammarAccess.getOutputTableAccess().getIsErrorRejectTableAssignment_10_1(), "rule__OutputTable__IsErrorRejectTableAssignment_10_1");
					put(grammarAccess.getOutputTableAccess().getIsJoinTableOfAssignment_11_1(), "rule__OutputTable__IsJoinTableOfAssignment_11_1");
					put(grammarAccess.getOutputTableAccess().getMapperTableEntriesAssignment_12(), "rule__OutputTable__MapperTableEntriesAssignment_12");
					put(grammarAccess.getMapperTableEntryAccess().getNameAssignment_4(), "rule__MapperTableEntry__NameAssignment_4");
					put(grammarAccess.getMapperTableEntryAccess().getTypeAssignment_5_2(), "rule__MapperTableEntry__TypeAssignment_5_2");
					put(grammarAccess.getMapperTableEntryAccess().getNullableAssignment_6_2(), "rule__MapperTableEntry__NullableAssignment_6_2");
					put(grammarAccess.getMapperTableEntryAccess().getExpressionAssignment_7_2(), "rule__MapperTableEntry__ExpressionAssignment_7_2");
					put(grammarAccess.getNodeTypeAccess().getComponentNameAssignment_4_1(), "rule__NodeType__ComponentNameAssignment_4_1");
					put(grammarAccess.getNodeTypeAccess().getElementParameterAssignment_5_1(), "rule__NodeType__ElementParameterAssignment_5_1");
					put(grammarAccess.getNodeTypeAccess().getPosXAssignment_6_1_0(), "rule__NodeType__PosXAssignment_6_1_0");
					put(grammarAccess.getNodeTypeAccess().getPosYAssignment_6_1_2(), "rule__NodeType__PosYAssignment_6_1_2");
					put(grammarAccess.getNodeTypeAccess().getMetadataAssignment_8(), "rule__NodeType__MetadataAssignment_8");
					put(grammarAccess.getNodeTypeAccess().getElementParameterAssignment_11(), "rule__NodeType__ElementParameterAssignment_11");
					put(grammarAccess.getNodeTypeAccess().getElementParameterAssignment_12_1(), "rule__NodeType__ElementParameterAssignment_12_1");
					put(grammarAccess.getNodeTypeAccess().getMetadataAssignment_14(), "rule__NodeType__MetadataAssignment_14");
					put(grammarAccess.getNodeTypeAccess().getNodeDataAssignment_15(), "rule__NodeType__NodeDataAssignment_15");
					put(grammarAccess.getContextTypeAccess().getNameAssignment_3_1(), "rule__ContextType__NameAssignment_3_1");
					put(grammarAccess.getContextTypeAccess().getConfirmationNeededAssignment_4_1(), "rule__ContextType__ConfirmationNeededAssignment_4_1");
					put(grammarAccess.getContextTypeAccess().getContextParameterAssignment_5_0(), "rule__ContextType__ContextParameterAssignment_5_0");
					put(grammarAccess.getContextTypeAccess().getContextParameterAssignment_5_1_1(), "rule__ContextType__ContextParameterAssignment_5_1_1");
					put(grammarAccess.getContextParameterTypeAccess().getNameAssignment_3_1(), "rule__ContextParameterType__NameAssignment_3_1");
					put(grammarAccess.getContextParameterTypeAccess().getTypeAssignment_4_1(), "rule__ContextParameterType__TypeAssignment_4_1");
					put(grammarAccess.getContextParameterTypeAccess().getValueAssignment_5_1(), "rule__ContextParameterType__ValueAssignment_5_1");
					put(grammarAccess.getContextParameterTypeAccess().getCommentAssignment_6_1(), "rule__ContextParameterType__CommentAssignment_6_1");
					put(grammarAccess.getContextParameterTypeAccess().getPromptAssignment_7_1(), "rule__ContextParameterType__PromptAssignment_7_1");
					put(grammarAccess.getContextParameterTypeAccess().getPromptNeededAssignment_8_1(), "rule__ContextParameterType__PromptNeededAssignment_8_1");
					put(grammarAccess.getContextParameterTypeAccess().getRepositoryContextIdAssignment_9_1(), "rule__ContextParameterType__RepositoryContextIdAssignment_9_1");
					put(grammarAccess.getUniqueNameTypeAccess().getValueAssignment(), "rule__UniqueNameType__ValueAssignment");
					put(grammarAccess.getConnectionTypeAccess().getConnectorNameAssignment_3_1(), "rule__ConnectionType__ConnectorNameAssignment_3_1");
					put(grammarAccess.getConnectionTypeAccess().getLabelAssignment_4_2(), "rule__ConnectionType__LabelAssignment_4_2");
					put(grammarAccess.getConnectionTypeAccess().getLineStyleAssignment_5_2(), "rule__ConnectionType__LineStyleAssignment_5_2");
					put(grammarAccess.getConnectionTypeAccess().getMergeOrderAssignment_6_2(), "rule__ConnectionType__MergeOrderAssignment_6_2");
					put(grammarAccess.getConnectionTypeAccess().getMetanameAssignment_7_2(), "rule__ConnectionType__MetanameAssignment_7_2");
					put(grammarAccess.getConnectionTypeAccess().getOutputIdAssignment_8_2(), "rule__ConnectionType__OutputIdAssignment_8_2");
					put(grammarAccess.getConnectionTypeAccess().getSourceAssignment_9_2(), "rule__ConnectionType__SourceAssignment_9_2");
					put(grammarAccess.getConnectionTypeAccess().getTargetAssignment_10_2(), "rule__ConnectionType__TargetAssignment_10_2");
					put(grammarAccess.getConnectionTypeAccess().getElementParameterAssignment_11_1(), "rule__ConnectionType__ElementParameterAssignment_11_1");
					put(grammarAccess.getNoteTypeAccess().getOpaqueAssignment_2_1(), "rule__NoteType__OpaqueAssignment_2_1");
					put(grammarAccess.getNoteTypeAccess().getPosXAssignment_3_2(), "rule__NoteType__PosXAssignment_3_2");
					put(grammarAccess.getNoteTypeAccess().getPosYAssignment_3_4(), "rule__NoteType__PosYAssignment_3_4");
					put(grammarAccess.getNoteTypeAccess().getTextAssignment_4_1(), "rule__NoteType__TextAssignment_4_1");
					put(grammarAccess.getNoteTypeAccess().getElementParameterAssignment_5(), "rule__NoteType__ElementParameterAssignment_5");
					put(grammarAccess.getNoteTypeAccess().getElementParameterAssignment_6_1(), "rule__NoteType__ElementParameterAssignment_6_1");
					put(grammarAccess.getElementParameterTypeAccess().getNameAssignment_1_0(), "rule__ElementParameterType__NameAssignment_1_0");
					put(grammarAccess.getElementParameterTypeAccess().getValueAssignment_1_2(), "rule__ElementParameterType__ValueAssignment_1_2");
					put(grammarAccess.getSchemaElementParameterTypeAccess().getNameAssignment_1_0(), "rule__SchemaElementParameterType__NameAssignment_1_0");
					put(grammarAccess.getSchemaElementParameterTypeAccess().getElementValueAssignment_1_2(), "rule__SchemaElementParameterType__ElementValueAssignment_1_2");
					put(grammarAccess.getSchemaElementParameterTypeAccess().getElementValueAssignment_1_3_1(), "rule__SchemaElementParameterType__ElementValueAssignment_1_3_1");
					put(grammarAccess.getElementValueTypeAccess().getElementRefAssignment_1_1(), "rule__ElementValueType__ElementRefAssignment_1_1");
					put(grammarAccess.getElementValueTypeAccess().getValueAssignment_2_1(), "rule__ElementValueType__ValueAssignment_2_1");
					put(grammarAccess.getElementValueTypeAccess().getTypeAssignment_3_1(), "rule__ElementValueType__TypeAssignment_3_1");
					put(grammarAccess.getMetadataTypeAccess().getNameAssignment_3_1(), "rule__MetadataType__NameAssignment_3_1");
					put(grammarAccess.getMetadataTypeAccess().getConnectorAssignment_4_1(), "rule__MetadataType__ConnectorAssignment_4_1");
					put(grammarAccess.getMetadataTypeAccess().getLabelAssignment_5_1(), "rule__MetadataType__LabelAssignment_5_1");
					put(grammarAccess.getMetadataTypeAccess().getCommentAssignment_6_1(), "rule__MetadataType__CommentAssignment_6_1");
					put(grammarAccess.getMetadataTypeAccess().getSourceAssignment_7_1(), "rule__MetadataType__SourceAssignment_7_1");
					put(grammarAccess.getMetadataTypeAccess().getColumnAssignment_8(), "rule__MetadataType__ColumnAssignment_8");
					put(grammarAccess.getColumnTypeAccess().getNameAssignment_3_1(), "rule__ColumnType__NameAssignment_3_1");
					put(grammarAccess.getColumnTypeAccess().getTypeAssignment_4_2(), "rule__ColumnType__TypeAssignment_4_2");
					put(grammarAccess.getColumnTypeAccess().getKeyAssignment_5_2(), "rule__ColumnType__KeyAssignment_5_2");
					put(grammarAccess.getColumnTypeAccess().getNullableAssignment_6_2(), "rule__ColumnType__NullableAssignment_6_2");
					put(grammarAccess.getColumnTypeAccess().getDefaultValueAssignment_7_2(), "rule__ColumnType__DefaultValueAssignment_7_2");
					put(grammarAccess.getColumnTypeAccess().getLengthAssignment_8_2(), "rule__ColumnType__LengthAssignment_8_2");
					put(grammarAccess.getColumnTypeAccess().getCommentAssignment_9_2(), "rule__ColumnType__CommentAssignment_9_2");
					put(grammarAccess.getColumnTypeAccess().getOriginalDbColumnNameAssignment_10_2(), "rule__ColumnType__OriginalDbColumnNameAssignment_10_2");
					put(grammarAccess.getColumnTypeAccess().getPatternAssignment_11_2(), "rule__ColumnType__PatternAssignment_11_2");
					put(grammarAccess.getColumnTypeAccess().getPrecisionAssignment_12_2(), "rule__ColumnType__PrecisionAssignment_12_2");
					put(grammarAccess.getColumnTypeAccess().getSourceTypeAssignment_13_2(), "rule__ColumnType__SourceTypeAssignment_13_2");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.talend.metalanguage.job.ui.contentassist.antlr.internal.InternalJobParser typedParser = (org.talend.metalanguage.job.ui.contentassist.antlr.internal.InternalJobParser) parser;
			typedParser.entryRuleProcessType();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public JobGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(JobGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
