<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="testcontainer" nsURI="http://www.talend.com/testcontainer.ecore"
    nsPrefix="testcontainer">
  <eClassifiers xsi:type="ecore:EClass" name="TestContainer" eSuperTypes="../../org.talend.model/model/TalendFile.ecore#//ProcessType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="testContainerNodes" upperBound="-1"
        eType="#//TestContainerNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="OriginalNodes" upperBound="-1"
        eType="#//OriginalNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="originalJobID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TestContainerNode" eSuperTypes="../../org.talend.model/model/TalendFile.ecore#//NodeType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="input" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OriginalNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uniqueName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="posX" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="posY" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Int"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="start" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
</ecore:EPackage>
