<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="properties"
    nsURI="http://www.talend.org/properties" nsPrefix="TalendProperties">
  <eClassifiers xsi:type="ecore:EClass" name="Project">
    <eStructuralFeatures xsi:type="ecore:EReference" name="technicalStatus" upperBound="-1"
        eType="#//Status" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="documentationStatus" upperBound="-1"
        eType="#//Status" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="technicalLabel" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="local" unique="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="folders" unique="false"
        upperBound="-1" eType="#//FolderItem" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deleted" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deleteDate" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="creationDate" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="author" eType="#//User"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="userAuthorization" upperBound="-1"
        eType="#//UserProjectAuthorization" eOpposite="#//UserProjectAuthorization/project"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allowedComponents" upperBound="-1"
        eType="#//ProjectComponentAuthorisation" eOpposite="#//ProjectComponentAuthorisation/project"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedProjects" upperBound="-1"
        eType="#//ProjectReference" eOpposite="#//ProjectReference/project"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="availableRefProject" upperBound="-1"
        eType="#//ProjectReference" eOpposite="#//ProjectReference/referencedProject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProjectComponentAuthorisation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="project" lowerBound="1"
        eType="#//Project" eOpposite="#//Project/allowedComponents"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="1"
        eType="#//Component" eOpposite="#//Component/projects"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProjectReference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="project" lowerBound="1"
        eType="#//Project" eOpposite="#//Project/referencedProjects"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedProject" lowerBound="1"
        eType="#//Project" eOpposite="#//Project/availableRefProject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Status">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ItemState">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deleted" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="locked" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="locker" eType="#//User"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lockDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="commitDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="purpose" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="creationDate" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modificationDate" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="statusCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="item" eType="#//Item" eOpposite="#//Item/property"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="author" eType="#//User"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Item" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" eType="#//Property"
        eOpposite="#//Property/item"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" eType="#//ItemState"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BusinessProcessItem" eSuperTypes="#//Item">
    <eStructuralFeatures xsi:type="ecore:EReference" name="notation" eType="ecore:EClass ../../../plugin/org.eclipse.gmf.runtime.notation/model/notation.ecore#//Diagram"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="semantic" eType="ecore:EClass Business.ecore#//BusinessProcess"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="notationHolder" eType="#//NotationHolder"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FileItem" abstract="true" eSuperTypes="#//Item">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="extension" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="content" eType="#//ByteArray"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ByteArray">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="innerContent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DocumentationItem" eSuperTypes="#//FileItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="RoutineItem" eSuperTypes="#//FileItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="builtIn" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectionItem" eSuperTypes="#//Item">
    <eStructuralFeatures xsi:type="ecore:EReference" name="connection" eType="ecore:EClass metadata.ecore#//Connection"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DelimitedFileConnectionItem" eSuperTypes="#//ConnectionItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="PositionalFileConnectionItem" eSuperTypes="#//ConnectionItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="RegExFileConnectionItem" eSuperTypes="#//ConnectionItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="CSVFileConnectionItem" eSuperTypes="#//DelimitedFileConnectionItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="DatabaseConnectionItem" eSuperTypes="#//ConnectionItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="XmlFileConnectionItem" eSuperTypes="#//ConnectionItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="LdifFileConnectionItem" eSuperTypes="#//ConnectionItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessItem" eSuperTypes="#//Item">
    <eStructuralFeatures xsi:type="ecore:EReference" name="process" eType="ecore:EClass TalendFile.ecore#//ProcessType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserRole">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="localizedLabel" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="User">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="login" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="creationDate" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deleteDate" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deleted" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="allowedToModifyComponents"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Comment" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="role" unique="false" lowerBound="1"
        eType="#//UserRole"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="projectAuthorization" upperBound="-1"
        eType="#//UserProjectAuthorization" eOpposite="#//UserProjectAuthorization/user"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FolderItem" eSuperTypes="#//Item">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" unique="false"
        upperBound="-1" eType="#//Item" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" unique="false" lowerBound="1"
        eType="#//FolderType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FolderType">
    <eLiterals name="FOLDER" literal="FOLDER"/>
    <eLiterals name="SYSTEM_FOLDER" value="1"/>
    <eLiterals name="STABLE_SYSTEM_FOLDER" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastUpdateDate" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="author" unique="false"
        lowerBound="1" eType="#//User"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="creationDate" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deleteDate" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deleted" unique="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileDescriptor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="projects" upperBound="-1"
        eType="#//ProjectComponentAuthorisation" eOpposite="#//ProjectComponentAuthorisation/component"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NotationHolder">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="notationString" eType="ecore:EDataType ../../../plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserProjectAuthorization">
    <eStructuralFeatures xsi:type="ecore:EReference" name="user" eType="#//User" eOpposite="#//User/projectAuthorization"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="project" eType="#//Project"
        eOpposite="#//Project/userAuthorization"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" unique="false" eType="#//UserProjectAuthorizationType"
        defaultValueLiteral="ReadWrite"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UserProjectAuthorizationType">
    <eLiterals name="ReadWrite" value="1"/>
    <eLiterals name="ReadOnly" value="2"/>
  </eClassifiers>
</ecore:EPackage>
