
CREATE TABLE talend_dq.ANALYSIS (
                A_ID INT(12) AUTO_INCREMENT NOT NULL,
                R_ID INT(12) NOT NULL,
                DURATION INT(10) NOT NULL,
                LABEL VARCHAR(50) NOT NULL,
                CREATION TIMESTAMP NOT NULL,
                AUTHOR VARCHAR(50) NOT NULL,
                DATA_FILTER VARCHAR(255) NOT NULL,
                PRIMARY KEY (A_ID)
) ENGINE=InnoDB;


CREATE TABLE talend_dq.SIMPLE_INDICATOR (
                SI_ID INT(12) AUTO_INCREMENT NOT NULL,
                COMPUTE_DATE INT(12) NOT NULL,
                ELEMENT INT(12) NOT NULL,
                INDICATOR INT(12) NOT NULL,
                A_ID INT(12) NOT NULL,
                INDICATOR_VALUE INT(19) NOT NULL,
                PRIMARY KEY (SI_ID)
) ENGINE=InnoDB;

CREATE TABLE talend_dq.INDICATOR_DEF (
                ID_ID INT(12) AUTO_INCREMENT NOT NULL,
                LABEL VARCHAR(50) NOT NULL,
                TYPE VARCHAR(50) NOT NULL,
                CATEGORY VARCHAR(50) NOT NULL,
                SUBCATEGORY VARCHAR(50) NOT NULL,
                PRIMARY KEY (ID_ID)
) ENGINE=InnoDB;

CREATE TABLE talend_dq.ANALYZED_ELEMENT (
                AE_ID INT(12) AUTO_INCREMENT NOT NULL,
                CONNECTION_NAME VARCHAR(50) NOT NULL,
                CATALOG_NAME VARCHAR(50) NOT NULL,
                SCHEMA_NAME VARCHAR(10) NOT NULL,
                TABLE_NAME VARCHAR(50) NOT NULL,
                COLUMN_NAME VARCHAR(50) NOT NULL,
                PRIMARY KEY (AE_ID)
) ENGINE=InnoDB;

CREATE TABLE talend_dq.CALENDAR (
                C_ID INT(12) AUTO_INCREMENT NOT NULL,
                USUAL_DATE DATE NOT NULL,
                PRIMARY KEY (C_ID)
) ENGINE=InnoDB;

CREATE TABLE talend_dq.REPORT (
                R_ID INT(12) AUTO_INCREMENT NOT NULL,
                CREATION TIMESTAMP NOT NULL,
                LABEL VARCHAR(50) NOT NULL,
                AUTHOR VARCHAR(50) NOT NULL,
                PRIMARY KEY (R_ID)
) ENGINE=InnoDB;

ALTER TABLE talend_dq.SIMPLE_INDICATOR ADD CONSTRAINT New_Table_New_Table2_fk
FOREIGN KEY (A_ID)
REFERENCES talend_dq.ANALYSIS (A_ID);

ALTER TABLE talend_dq.SIMPLE_INDICATOR ADD CONSTRAINT INDICATOR_DEF_SIMPLE_INDICATOR_fk
FOREIGN KEY (INDICATOR)
REFERENCES talend_dq.INDICATOR_DEF (ID_ID);

ALTER TABLE talend_dq.SIMPLE_INDICATOR ADD CONSTRAINT ANALYZED_ELEMENT_SIMPLE_INDICATOR_fk
FOREIGN KEY (ELEMENT)
REFERENCES talend_dq.ANALYZED_ELEMENT (AE_ID);

ALTER TABLE talend_dq.SIMPLE_INDICATOR ADD CONSTRAINT CALENDAR_SIMPLE_INDICATOR_fk
FOREIGN KEY (COMPUTE_DATE)
REFERENCES talend_dq.CALENDAR (C_ID);

ALTER TABLE talend_dq.ANALYSIS ADD CONSTRAINT REPORT_Analysis_fk
FOREIGN KEY (R_ID)
REFERENCES talend_dq.REPORT (R_ID);
