
CREATE TABLE talend_dq.TDQ_ANALYSIS (
                AN_PK INT(12) AUTO_INCREMENT NOT NULL,
                AN_UUID VARCHAR(50) NOT NULL,
                AN_LABEL VARCHAR(50) NOT NULL,
                AN_CREATION_DATE TIMESTAMP NOT NULL,
                AN_AUTHOR VARCHAR(50) NOT NULL,
                AN_DATA_FILTER VARCHAR(255) NOT NULL,
                AN_STATUS VARCHAR(20) NOT NULL,
                REP_UUID VARCHAR(50) NOT NULL,
                REP_CREATION_DATE TIMESTAMP NOT NULL,
                REP_LABEL VARCHAR(50) NOT NULL,
                REP_AUTHOR VARCHAR(50) NOT NULL,
                REP_STATUS VARCHAR(20) NOT NULL,
                AN_BEGIN_DATE TIMESTAMP NOT NULL,
                AN_END_DATE TIMESTAMP NOT NULL,
                AN_VERSION INT(10) NOT NULL,
                PRIMARY KEY (AN_PK)
) ENGINE=InnoDB;

CREATE TABLE talend_dq.TDQ_INDICATOR_VALUE (
                INDV_PK INT(12) AUTO_INCREMENT NOT NULL,
                OPTION_PK INT(12) NOT NULL,
                INTERVAL_PK INT(12) NOT NULL,
                ANALYSIS_PK INT(12) NOT NULL,
                ELEMENT_PK INT(12) NOT NULL,
                INDICATOR_PK INT(12) NOT NULL,
                TIME_PK INT(12) NOT NULL,
                CALENDAR_PK INT(12) NOT NULL,
                VALUE_PK INT(12) NOT NULL,
                AN_DURATION INT(10) NOT NULL,
                INDV_REAL_VALUE DOUBLE PRECISION NULL,
                INDV_INT_VALUE INT(19) NULL,
                INDV_ROW_COUNT INT(12) NULL,
                INDV_VALUE_TYPE_INDICATOR CHAR(1) NOT NULL,
                PRIMARY KEY (INDV_PK)
) ENGINE=InnoDB;

CREATE TABLE talend_dq.TDQ_INDICATOR_DEFINITION (
                IND_PK INT(12) AUTO_INCREMENT NOT NULL,
                IND_LABEL VARCHAR(50) NOT NULL,
                IND_TYPE VARCHAR(50) NOT NULL,
                IND_CATEGORY VARCHAR(50) NOT NULL,
                IND_SUBCATEGORY VARCHAR(50) NOT NULL,
                IND_BEGIN_DATE TIMESTAMP NOT NULL,
                IND_END_DATE TIMESTAMP NOT NULL,
                IND_VERSION INT(10) NOT NULL,
                PRIMARY KEY (IND_PK)
) ENGINE=InnoDB;

CREATE TABLE talend_dq.TDQ_ANALYZED_ELEMENT (
                ELT_PK INT(12) AUTO_INCREMENT NOT NULL,
                ELT_UUID VARCHAR(50) NOT NULL,
                ELT_CONNECTION_UUID VARCHAR(50) NOT NULL,
                ELT_CONNECTION_NAME VARCHAR(50) NOT NULL,
                ELT_CATALOG_NAME VARCHAR(50) NOT NULL,
                ELT_SCHEMA_NAME VARCHAR(50) NOT NULL,
                ELT_TABLE_NAME VARCHAR(50) NOT NULL,
                ELT_COLUMN_NAME VARCHAR(50) NOT NULL,
                ELT_BEGIN_DATE TIMESTAMP NOT NULL,
                ELT_END_DATE TIMESTAMP NOT NULL,
                ELT_VERSION INT(10) NOT NULL,
                PRIMARY KEY (ELT_PK)
) ENGINE=InnoDB;

CREATE TABLE talend_dq.TDQ_CALENDAR (
                CAL_PK INT(12) AUTO_INCREMENT NOT NULL,
                CAL_DATE DATE NOT NULL,
                CAL_DAY_IN_MONTH INT(2) NOT NULL,
                CAL_DAY_IN_YEAR INT(3) NOT NULL,
                CAL_LAST_WEEK_DAY INT(1) NOT NULL,
                CAL_LAST_MONTH_DAY INT(2) NOT NULL,
                CAL_WEEK_DAY INT(1) NOT NULL,
                CAL_DAY_NAME VARCHAR(20) NOT NULL,
                CAL_WEEK_NUM INT(2) NOT NULL,
                CAL_MONTH INT(2) NOT NULL,
                CAL_MONTH_NAME VARCHAR(20) NOT NULL,
                CAL_YEAR INT(4) NOT NULL,
                CAL_MONTH_PERIOD CHAR(6) NOT NULL,
                CAL_QUARTER INT(1) NOT NULL,
                CAL_QUARTER_PERIOD CHAR(5) NOT NULL,
                CAL_SEMESTER INT(1) NOT NULL,
                CAL_DAY_OFF CHAR(1) NOT NULL,
                CAL_SPECIAL_DAY CHAR(1) NOT NULL,
                CAL_SPEC_DAY_LABEL VARCHAR(50) NOT NULL,
                PRIMARY KEY (CAL_PK)
) ENGINE=InnoDB;

CREATE TABLE talend_dq.TDQ_DAY_TIME (
                TIME_PK INT(12) AUTO_INCREMENT NOT NULL,
                TIME_HOUR INT(10) NOT NULL,
                TIME_MINUTE INT(10) NOT NULL,
                PRIMARY KEY (TIME_PK)
) ENGINE=InnoDB;

CREATE TABLE talend_dq.TDQ_VALUES (
                VAL_PK INT(12) AUTO_INCREMENT NOT NULL,
                VAL_STRING VARCHAR(255) NOT NULL,
                PRIMARY KEY (VAL_PK)
) ENGINE=InnoDB;

CREATE TABLE talend_dq.TDQ_INTERVAL (
                INT_PK INT(12) AUTO_INCREMENT NOT NULL,
                INT_LOWER_REAL DOUBLE PRECISION NOT NULL,
                INT_UPPER_REAL DOUBLE PRECISION NOT NULL,
                INT_LOWER_INT INT(12) NOT NULL,
                INT_UPPER_INT INT(12) NOT NULL,
                INT_DATA_FLAG CHAR(1) NOT NULL,
                INT_LABEL VARCHAR(50) NOT NULL,
                PRIMARY KEY (INT_PK)
) ENGINE=InnoDB;

CREATE TABLE talend_dq.TDQ_INDICATOR_OPTIONS (
                INO_PK INT(12) AUTO_INCREMENT NOT NULL,
                INO_CASE_SENSITIVE CHAR(1) NOT NULL,
                INO_REGEXP VARCHAR(255) NOT NULL,
                INO_COUNT_NULLS CHAR(1) NOT NULL,
                INO_COUNT_BLANKS INT(1) NOT NULL,
                PRIMARY KEY (INO_PK)
) ENGINE=InnoDB;

ALTER TABLE talend_dq.TDQ_INDICATOR_VALUE ADD CONSTRAINT TDQ_ANALYSIS_EXECUTION_TDQ_INDICATOR_VALUE_fk
FOREIGN KEY (ANALYSIS_PK)
REFERENCES talend_dq.TDQ_ANALYSIS (AN_PK);

ALTER TABLE talend_dq.TDQ_INDICATOR_VALUE ADD CONSTRAINT TDQ_INDICATOR_DEFINITION_TDQ_INDICATOR_VALUE_fk
FOREIGN KEY (INDICATOR_PK)
REFERENCES talend_dq.TDQ_INDICATOR_DEFINITION (IND_PK);

ALTER TABLE talend_dq.TDQ_INDICATOR_VALUE ADD CONSTRAINT TDQ_ANALYZED_ELEMENT_TDQ_INDICATOR_VALUE_fk
FOREIGN KEY (ELEMENT_PK)
REFERENCES talend_dq.TDQ_ANALYZED_ELEMENT (ELT_PK);

ALTER TABLE talend_dq.TDQ_INDICATOR_VALUE ADD CONSTRAINT TDQ_CALENDAR_TDQ_INDICATOR_VALUE_fk
FOREIGN KEY (CALENDAR_PK)
REFERENCES talend_dq.TDQ_CALENDAR (CAL_PK);

ALTER TABLE talend_dq.TDQ_INDICATOR_VALUE ADD CONSTRAINT TDQ_DAY_TIME_TDQ_INDICATOR_VALUE_fk
FOREIGN KEY (TIME_PK)
REFERENCES talend_dq.TDQ_DAY_TIME (TIME_PK);

ALTER TABLE talend_dq.TDQ_INDICATOR_VALUE ADD CONSTRAINT VALUES_TDQ_INDICATOR_VALUE_fk
FOREIGN KEY (VALUE_PK)
REFERENCES talend_dq.TDQ_VALUES (VAL_PK);

ALTER TABLE talend_dq.TDQ_INDICATOR_VALUE ADD CONSTRAINT TDQ_INTERVAL_TDQ_INDICATOR_VALUE_fk
FOREIGN KEY (INTERVAL_PK)
REFERENCES talend_dq.TDQ_INTERVAL (INT_PK);

ALTER TABLE talend_dq.TDQ_INDICATOR_VALUE ADD CONSTRAINT TDQ_REGEXP_TDQ_INDICATOR_VALUE_fk
FOREIGN KEY (OPTION_PK)
REFERENCES talend_dq.TDQ_INDICATOR_OPTIONS (INO_PK);
