/*
* generated by Xtext
*/
package org.talend.metalanguage.job.ui.contentassist;

import org.talend.metalanguage.job.ui.contentassist.AbstractJobProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class JobProposalProvider extends AbstractJobProposalProvider {

}
