/*
 * generated by Xtext
 */
package org.talend.metalanguage.job.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class JobUiModule extends org.talend.metalanguage.job.ui.AbstractJobUiModule {
	public JobUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
