/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.talend.designer.xmlmap.model.emf.xmlmap.validation;

import org.eclipse.emf.common.util.EList;
import org.talend.designer.xmlmap.model.emf.xmlmap.TreeNode;

/**
 * A sample validator interface for {@link org.talend.designer.xmlmap.model.emf.xmlmap.InputXmlTree}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface InputXmlTreeValidator {
	boolean validate();

	boolean validateNodes(EList<TreeNode> value);

	boolean validateNodes(TreeNode value);
	boolean validateName(String value);
	boolean validateLookup(boolean value);
}
