/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.talend.designer.xmlmap.model.emf.xmlmap.validation;

import org.eclipse.emf.common.util.EList;

import org.talend.designer.xmlmap.model.emf.xmlmap.TreeNode;

/**
 * A sample validator interface for {@link org.talend.designer.xmlmap.model.emf.xmlmap.TreeNode}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TreeNodeValidator {
	boolean validate();

	boolean validateChildren(EList<TreeNode> value);
	boolean validateParent(TreeNode value);
	boolean validateName(String value);
	boolean validateExpression(String value);
	boolean validateType(String value);
	boolean validateNullable(boolean value);
	boolean validateXpath(String value);
	boolean validateIsLoop(boolean value);
}
