/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.talend.core.model.properties.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import org.talend.core.model.properties.util.PropertiesAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class PropertiesItemProviderAdapterFactory extends PropertiesAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
    /**
     * This keeps track of the root adapter factory that delegates to this adapter factory.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ComposedAdapterFactory parentAdapterFactory;

    /**
     * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected IChangeNotifier changeNotifier = new ChangeNotifier();

    /**
     * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected Collection supportedTypes = new ArrayList();

    /**
     * This constructs an instance.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public PropertiesItemProviderAdapterFactory() {
        supportedTypes.add(IEditingDomainItemProvider.class);
        supportedTypes.add(IStructuredItemContentProvider.class);
        supportedTypes.add(ITreeItemContentProvider.class);
        supportedTypes.add(IItemLabelProvider.class);
        supportedTypes.add(IItemPropertySource.class);
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.Project} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ProjectItemProvider projectItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.Project}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createProjectAdapter() {
        if (projectItemProvider == null) {
            projectItemProvider = new ProjectItemProvider(this);
        }

        return projectItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.ProjectComponentAuthorisation} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ProjectComponentAuthorisationItemProvider projectComponentAuthorisationItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.ProjectComponentAuthorisation}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createProjectComponentAuthorisationAdapter() {
        if (projectComponentAuthorisationItemProvider == null) {
            projectComponentAuthorisationItemProvider = new ProjectComponentAuthorisationItemProvider(this);
        }

        return projectComponentAuthorisationItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.ProjectReference} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ProjectReferenceItemProvider projectReferenceItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.ProjectReference}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createProjectReferenceAdapter() {
        if (projectReferenceItemProvider == null) {
            projectReferenceItemProvider = new ProjectReferenceItemProvider(this);
        }

        return projectReferenceItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.Status} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected StatusItemProvider statusItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.Status}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createStatusAdapter() {
        if (statusItemProvider == null) {
            statusItemProvider = new StatusItemProvider(this);
        }

        return statusItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.ItemState} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ItemStateItemProvider itemStateItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.ItemState}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createItemStateAdapter() {
        if (itemStateItemProvider == null) {
            itemStateItemProvider = new ItemStateItemProvider(this);
        }

        return itemStateItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.Property} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected PropertyItemProvider propertyItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.Property}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createPropertyAdapter() {
        if (propertyItemProvider == null) {
            propertyItemProvider = new PropertyItemProvider(this);
        }

        return propertyItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.LinkDocumentationItem} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected LinkDocumentationItemItemProvider linkDocumentationItemItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.LinkDocumentationItem}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createLinkDocumentationItemAdapter() {
        if (linkDocumentationItemItemProvider == null) {
            linkDocumentationItemItemProvider = new LinkDocumentationItemItemProvider(this);
        }

        return linkDocumentationItemItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.LinkType} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected LinkTypeItemProvider linkTypeItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.LinkType}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createLinkTypeAdapter() {
        if (linkTypeItemProvider == null) {
            linkTypeItemProvider = new LinkTypeItemProvider(this);
        }

        return linkTypeItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.BusinessProcessItem} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected BusinessProcessItemItemProvider businessProcessItemItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.BusinessProcessItem}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createBusinessProcessItemAdapter() {
        if (businessProcessItemItemProvider == null) {
            businessProcessItemItemProvider = new BusinessProcessItemItemProvider(this);
        }

        return businessProcessItemItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.ByteArray} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ByteArrayItemProvider byteArrayItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.ByteArray}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createByteArrayAdapter() {
        if (byteArrayItemProvider == null) {
            byteArrayItemProvider = new ByteArrayItemProvider(this);
        }

        return byteArrayItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.DocumentationItem} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected DocumentationItemItemProvider documentationItemItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.DocumentationItem}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createDocumentationItemAdapter() {
        if (documentationItemItemProvider == null) {
            documentationItemItemProvider = new DocumentationItemItemProvider(this);
        }

        return documentationItemItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.RoutineItem} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected RoutineItemItemProvider routineItemItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.RoutineItem}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createRoutineItemAdapter() {
        if (routineItemItemProvider == null) {
            routineItemItemProvider = new RoutineItemItemProvider(this);
        }

        return routineItemItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.ConnectionItem} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ConnectionItemItemProvider connectionItemItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.ConnectionItem}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createConnectionItemAdapter() {
        if (connectionItemItemProvider == null) {
            connectionItemItemProvider = new ConnectionItemItemProvider(this);
        }

        return connectionItemItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.SnippetVariable} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected SnippetVariableItemProvider snippetVariableItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.SnippetVariable}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createSnippetVariableAdapter() {
        if (snippetVariableItemProvider == null) {
            snippetVariableItemProvider = new SnippetVariableItemProvider(this);
        }

        return snippetVariableItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.SnippetItem} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected SnippetItemItemProvider snippetItemItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.SnippetItem}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createSnippetItemAdapter() {
        if (snippetItemItemProvider == null) {
            snippetItemItemProvider = new SnippetItemItemProvider(this);
        }

        return snippetItemItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.DelimitedFileConnectionItem} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected DelimitedFileConnectionItemItemProvider delimitedFileConnectionItemItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.DelimitedFileConnectionItem}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createDelimitedFileConnectionItemAdapter() {
        if (delimitedFileConnectionItemItemProvider == null) {
            delimitedFileConnectionItemItemProvider = new DelimitedFileConnectionItemItemProvider(this);
        }

        return delimitedFileConnectionItemItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.PositionalFileConnectionItem} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected PositionalFileConnectionItemItemProvider positionalFileConnectionItemItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.PositionalFileConnectionItem}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createPositionalFileConnectionItemAdapter() {
        if (positionalFileConnectionItemItemProvider == null) {
            positionalFileConnectionItemItemProvider = new PositionalFileConnectionItemItemProvider(this);
        }

        return positionalFileConnectionItemItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.RegExFileConnectionItem} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected RegExFileConnectionItemItemProvider regExFileConnectionItemItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.RegExFileConnectionItem}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createRegExFileConnectionItemAdapter() {
        if (regExFileConnectionItemItemProvider == null) {
            regExFileConnectionItemItemProvider = new RegExFileConnectionItemItemProvider(this);
        }

        return regExFileConnectionItemItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.CSVFileConnectionItem} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected CSVFileConnectionItemItemProvider csvFileConnectionItemItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.CSVFileConnectionItem}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createCSVFileConnectionItemAdapter() {
        if (csvFileConnectionItemItemProvider == null) {
            csvFileConnectionItemItemProvider = new CSVFileConnectionItemItemProvider(this);
        }

        return csvFileConnectionItemItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.DatabaseConnectionItem} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected DatabaseConnectionItemItemProvider databaseConnectionItemItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.DatabaseConnectionItem}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createDatabaseConnectionItemAdapter() {
        if (databaseConnectionItemItemProvider == null) {
            databaseConnectionItemItemProvider = new DatabaseConnectionItemItemProvider(this);
        }

        return databaseConnectionItemItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.SAPConnectionItem} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected SAPConnectionItemItemProvider sapConnectionItemItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.SAPConnectionItem}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createSAPConnectionItemAdapter() {
        if (sapConnectionItemItemProvider == null) {
            sapConnectionItemItemProvider = new SAPConnectionItemItemProvider(this);
        }

        return sapConnectionItemItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.XmlFileConnectionItem} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected XmlFileConnectionItemItemProvider xmlFileConnectionItemItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.XmlFileConnectionItem}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createXmlFileConnectionItemAdapter() {
        if (xmlFileConnectionItemItemProvider == null) {
            xmlFileConnectionItemItemProvider = new XmlFileConnectionItemItemProvider(this);
        }

        return xmlFileConnectionItemItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.LdifFileConnectionItem} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected LdifFileConnectionItemItemProvider ldifFileConnectionItemItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.LdifFileConnectionItem}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createLdifFileConnectionItemAdapter() {
        if (ldifFileConnectionItemItemProvider == null) {
            ldifFileConnectionItemItemProvider = new LdifFileConnectionItemItemProvider(this);
        }

        return ldifFileConnectionItemItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.ExcelFileConnectionItem} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ExcelFileConnectionItemItemProvider excelFileConnectionItemItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.ExcelFileConnectionItem}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createExcelFileConnectionItemAdapter() {
        if (excelFileConnectionItemItemProvider == null) {
            excelFileConnectionItemItemProvider = new ExcelFileConnectionItemItemProvider(this);
        }

        return excelFileConnectionItemItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.EbcdicConnectionItem} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected EbcdicConnectionItemItemProvider ebcdicConnectionItemItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.EbcdicConnectionItem}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createEbcdicConnectionItemAdapter() {
        if (ebcdicConnectionItemItemProvider == null) {
            ebcdicConnectionItemItemProvider = new EbcdicConnectionItemItemProvider(this);
        }

        return ebcdicConnectionItemItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.MDMConnectionItem} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected MDMConnectionItemItemProvider mdmConnectionItemItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.MDMConnectionItem}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createMDMConnectionItemAdapter() {
        if (mdmConnectionItemItemProvider == null) {
            mdmConnectionItemItemProvider = new MDMConnectionItemItemProvider(this);
        }

        return mdmConnectionItemItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.ProcessItem} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ProcessItemItemProvider processItemItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.ProcessItem}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createProcessItemAdapter() {
        if (processItemItemProvider == null) {
            processItemItemProvider = new ProcessItemItemProvider(this);
        }

        return processItemItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.UserRole} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected UserRoleItemProvider userRoleItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.UserRole}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createUserRoleAdapter() {
        if (userRoleItemProvider == null) {
            userRoleItemProvider = new UserRoleItemProvider(this);
        }

        return userRoleItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.User} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected UserItemProvider userItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.User}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createUserAdapter() {
        if (userItemProvider == null) {
            userItemProvider = new UserItemProvider(this);
        }

        return userItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.FolderItem} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected FolderItemItemProvider folderItemItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.FolderItem}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createFolderItemAdapter() {
        if (folderItemItemProvider == null) {
            folderItemItemProvider = new FolderItemItemProvider(this);
        }

        return folderItemItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.Component} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ComponentItemProvider componentItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.Component}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createComponentAdapter() {
        if (componentItemProvider == null) {
            componentItemProvider = new ComponentItemProvider(this);
        }

        return componentItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.NotationHolder} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected NotationHolderItemProvider notationHolderItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.NotationHolder}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createNotationHolderAdapter() {
        if (notationHolderItemProvider == null) {
            notationHolderItemProvider = new NotationHolderItemProvider(this);
        }

        return notationHolderItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.UserProjectAuthorization} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected UserProjectAuthorizationItemProvider userProjectAuthorizationItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.UserProjectAuthorization}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createUserProjectAuthorizationAdapter() {
        if (userProjectAuthorizationItemProvider == null) {
            userProjectAuthorizationItemProvider = new UserProjectAuthorizationItemProvider(this);
        }

        return userProjectAuthorizationItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.ContextItem} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ContextItemItemProvider contextItemItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.ContextItem}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createContextItemAdapter() {
        if (contextItemItemProvider == null) {
            contextItemItemProvider = new ContextItemItemProvider(this);
        }

        return contextItemItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.SpagoBiServer} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected SpagoBiServerItemProvider spagoBiServerItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.SpagoBiServer}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createSpagoBiServerAdapter() {
        if (spagoBiServerItemProvider == null) {
            spagoBiServerItemProvider = new SpagoBiServerItemProvider(this);
        }

        return spagoBiServerItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.License} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected LicenseItemProvider licenseItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.License}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createLicenseAdapter() {
        if (licenseItemProvider == null) {
            licenseItemProvider = new LicenseItemProvider(this);
        }

        return licenseItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.GenericSchemaConnectionItem} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected GenericSchemaConnectionItemItemProvider genericSchemaConnectionItemItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.GenericSchemaConnectionItem}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createGenericSchemaConnectionItemAdapter() {
        if (genericSchemaConnectionItemItemProvider == null) {
            genericSchemaConnectionItemItemProvider = new GenericSchemaConnectionItemItemProvider(this);
        }

        return genericSchemaConnectionItemItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.UserModuleAuthorization} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected UserModuleAuthorizationItemProvider userModuleAuthorizationItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.UserModuleAuthorization}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createUserModuleAuthorizationAdapter() {
        if (userModuleAuthorizationItemProvider == null) {
            userModuleAuthorizationItemProvider = new UserModuleAuthorizationItemProvider(this);
        }

        return userModuleAuthorizationItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.LDAPSchemaConnectionItem} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected LDAPSchemaConnectionItemItemProvider ldapSchemaConnectionItemItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.LDAPSchemaConnectionItem}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createLDAPSchemaConnectionItemAdapter() {
        if (ldapSchemaConnectionItemItemProvider == null) {
            ldapSchemaConnectionItemItemProvider = new LDAPSchemaConnectionItemItemProvider(this);
        }

        return ldapSchemaConnectionItemItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.SalesforceSchemaConnectionItem} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected SalesforceSchemaConnectionItemItemProvider salesforceSchemaConnectionItemItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.SalesforceSchemaConnectionItem}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createSalesforceSchemaConnectionItemAdapter() {
        if (salesforceSchemaConnectionItemItemProvider == null) {
            salesforceSchemaConnectionItemItemProvider = new SalesforceSchemaConnectionItemItemProvider(this);
        }

        return salesforceSchemaConnectionItemItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.DashboardConnection} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected DashboardConnectionItemProvider dashboardConnectionItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.DashboardConnection}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createDashboardConnectionAdapter() {
        if (dashboardConnectionItemProvider == null) {
            dashboardConnectionItemProvider = new DashboardConnectionItemProvider(this);
        }

        return dashboardConnectionItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.ExecutionPlan} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ExecutionPlanItemProvider executionPlanItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.ExecutionPlan}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createExecutionPlanAdapter() {
        if (executionPlanItemProvider == null) {
            executionPlanItemProvider = new ExecutionPlanItemProvider(this);
        }

        return executionPlanItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.ExecutionPlanPart} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ExecutionPlanPartItemProvider executionPlanPartItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.ExecutionPlanPart}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createExecutionPlanPartAdapter() {
        if (executionPlanPartItemProvider == null) {
            executionPlanPartItemProvider = new ExecutionPlanPartItemProvider(this);
        }

        return executionPlanPartItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.ExecutionPlanPrm} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ExecutionPlanPrmItemProvider executionPlanPrmItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.ExecutionPlanPrm}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createExecutionPlanPrmAdapter() {
        if (executionPlanPrmItemProvider == null) {
            executionPlanPrmItemProvider = new ExecutionPlanPrmItemProvider(this);
        }

        return executionPlanPrmItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.ExecutionPlanPartCmdPrm} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ExecutionPlanPartCmdPrmItemProvider executionPlanPartCmdPrmItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.ExecutionPlanPartCmdPrm}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createExecutionPlanPartCmdPrmAdapter() {
        if (executionPlanPartCmdPrmItemProvider == null) {
            executionPlanPartCmdPrmItemProvider = new ExecutionPlanPartCmdPrmItemProvider(this);
        }

        return executionPlanPartCmdPrmItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.ExecutionPlanPartJobPrm} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ExecutionPlanPartJobPrmItemProvider executionPlanPartJobPrmItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.ExecutionPlanPartJobPrm}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createExecutionPlanPartJobPrmAdapter() {
        if (executionPlanPartJobPrmItemProvider == null) {
            executionPlanPartJobPrmItemProvider = new ExecutionPlanPartJobPrmItemProvider(this);
        }

        return executionPlanPartJobPrmItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.ExecutionServer} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ExecutionServerItemProvider executionServerItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.ExecutionServer}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createExecutionServerAdapter() {
        if (executionServerItemProvider == null) {
            executionServerItemProvider = new ExecutionServerItemProvider(this);
        }

        return executionServerItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.ExecutionTask} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ExecutionTaskItemProvider executionTaskItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.ExecutionTask}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createExecutionTaskAdapter() {
        if (executionTaskItemProvider == null) {
            executionTaskItemProvider = new ExecutionTaskItemProvider(this);
        }

        return executionTaskItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.ExecutionTaskCmdPrm} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ExecutionTaskCmdPrmItemProvider executionTaskCmdPrmItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.ExecutionTaskCmdPrm}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createExecutionTaskCmdPrmAdapter() {
        if (executionTaskCmdPrmItemProvider == null) {
            executionTaskCmdPrmItemProvider = new ExecutionTaskCmdPrmItemProvider(this);
        }

        return executionTaskCmdPrmItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.ExecutionTaskJobPrm} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ExecutionTaskJobPrmItemProvider executionTaskJobPrmItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.ExecutionTaskJobPrm}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createExecutionTaskJobPrmAdapter() {
        if (executionTaskJobPrmItemProvider == null) {
            executionTaskJobPrmItemProvider = new ExecutionTaskJobPrmItemProvider(this);
        }

        return executionTaskJobPrmItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.TaskExecutionHistory} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TaskExecutionHistoryItemProvider taskExecutionHistoryItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.TaskExecutionHistory}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createTaskExecutionHistoryAdapter() {
        if (taskExecutionHistoryItemProvider == null) {
            taskExecutionHistoryItemProvider = new TaskExecutionHistoryItemProvider(this);
        }

        return taskExecutionHistoryItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.PlanExecutionHistory} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected PlanExecutionHistoryItemProvider planExecutionHistoryItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.PlanExecutionHistory}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createPlanExecutionHistoryAdapter() {
        if (planExecutionHistoryItemProvider == null) {
            planExecutionHistoryItemProvider = new PlanExecutionHistoryItemProvider(this);
        }

        return planExecutionHistoryItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.TalendTrigger} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TalendTriggerItemProvider talendTriggerItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.TalendTrigger}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createTalendTriggerAdapter() {
        if (talendTriggerItemProvider == null) {
            talendTriggerItemProvider = new TalendTriggerItemProvider(this);
        }

        return talendTriggerItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.CronTalendTrigger} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected CronTalendTriggerItemProvider cronTalendTriggerItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.CronTalendTrigger}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createCronTalendTriggerAdapter() {
        if (cronTalendTriggerItemProvider == null) {
            cronTalendTriggerItemProvider = new CronTalendTriggerItemProvider(this);
        }

        return cronTalendTriggerItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.CronUITalendTrigger} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected CronUITalendTriggerItemProvider cronUITalendTriggerItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.CronUITalendTrigger}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createCronUITalendTriggerAdapter() {
        if (cronUITalendTriggerItemProvider == null) {
            cronUITalendTriggerItemProvider = new CronUITalendTriggerItemProvider(this);
        }

        return cronUITalendTriggerItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.SimpleTalendTrigger} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected SimpleTalendTriggerItemProvider simpleTalendTriggerItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.SimpleTalendTrigger}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createSimpleTalendTriggerAdapter() {
        if (simpleTalendTriggerItemProvider == null) {
            simpleTalendTriggerItemProvider = new SimpleTalendTriggerItemProvider(this);
        }

        return simpleTalendTriggerItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.ExecutionVirtualServer} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ExecutionVirtualServerItemProvider executionVirtualServerItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.ExecutionVirtualServer}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createExecutionVirtualServerAdapter() {
        if (executionVirtualServerItemProvider == null) {
            executionVirtualServerItemProvider = new ExecutionVirtualServerItemProvider(this);
        }

        return executionVirtualServerItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.FileTrigger} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected FileTriggerItemProvider fileTriggerItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.FileTrigger}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createFileTriggerAdapter() {
        if (fileTriggerItemProvider == null) {
            fileTriggerItemProvider = new FileTriggerItemProvider(this);
        }

        return fileTriggerItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.FileTriggerMask} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected FileTriggerMaskItemProvider fileTriggerMaskItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.FileTriggerMask}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createFileTriggerMaskAdapter() {
        if (fileTriggerMaskItemProvider == null) {
            fileTriggerMaskItemProvider = new FileTriggerMaskItemProvider(this);
        }

        return fileTriggerMaskItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.JobletProcessItem} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected JobletProcessItemItemProvider jobletProcessItemItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.JobletProcessItem}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createJobletProcessItemAdapter() {
        if (jobletProcessItemItemProvider == null) {
            jobletProcessItemItemProvider = new JobletProcessItemItemProvider(this);
        }

        return jobletProcessItemItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.JobDocumentationItem} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected JobDocumentationItemItemProvider jobDocumentationItemItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.JobDocumentationItem}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createJobDocumentationItemAdapter() {
        if (jobDocumentationItemItemProvider == null) {
            jobDocumentationItemItemProvider = new JobDocumentationItemItemProvider(this);
        }

        return jobDocumentationItemItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.JobletDocumentationItem} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected JobletDocumentationItemItemProvider jobletDocumentationItemItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.JobletDocumentationItem}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createJobletDocumentationItemAdapter() {
        if (jobletDocumentationItemItemProvider == null) {
            jobletDocumentationItemItemProvider = new JobletDocumentationItemItemProvider(this);
        }

        return jobletDocumentationItemItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.WSDLSchemaConnectionItem} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected WSDLSchemaConnectionItemItemProvider wsdlSchemaConnectionItemItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.WSDLSchemaConnectionItem}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createWSDLSchemaConnectionItemAdapter() {
        if (wsdlSchemaConnectionItemItemProvider == null) {
            wsdlSchemaConnectionItemItemProvider = new WSDLSchemaConnectionItemItemProvider(this);
        }

        return wsdlSchemaConnectionItemItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.SchemaInformation} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected SchemaInformationItemProvider schemaInformationItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.SchemaInformation}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createSchemaInformationAdapter() {
        if (schemaInformationItemProvider == null) {
            schemaInformationItemProvider = new SchemaInformationItemProvider(this);
        }

        return schemaInformationItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.Information} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected InformationItemProvider informationItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.Information}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createInformationAdapter() {
        if (informationItemProvider == null) {
            informationItemProvider = new InformationItemProvider(this);
        }

        return informationItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.SQLPatternItem} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected SQLPatternItemItemProvider sqlPatternItemItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.SQLPatternItem}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createSQLPatternItemAdapter() {
        if (sqlPatternItemItemProvider == null) {
            sqlPatternItemItemProvider = new SQLPatternItemItemProvider(this);
        }

        return sqlPatternItemItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.ComponentSetting} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ComponentSettingItemProvider componentSettingItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.ComponentSetting}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createComponentSettingAdapter() {
        if (componentSettingItemProvider == null) {
            componentSettingItemProvider = new ComponentSettingItemProvider(this);
        }

        return componentSettingItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.StatAndLogsSettings} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected StatAndLogsSettingsItemProvider statAndLogsSettingsItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.StatAndLogsSettings}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createStatAndLogsSettingsAdapter() {
        if (statAndLogsSettingsItemProvider == null) {
            statAndLogsSettingsItemProvider = new StatAndLogsSettingsItemProvider(this);
        }

        return statAndLogsSettingsItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.ImplicitContextSettings} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ImplicitContextSettingsItemProvider implicitContextSettingsItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.ImplicitContextSettings}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createImplicitContextSettingsAdapter() {
        if (implicitContextSettingsItemProvider == null) {
            implicitContextSettingsItemProvider = new ImplicitContextSettingsItemProvider(this);
        }

        return implicitContextSettingsItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.SoaOperation} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected SoaOperationItemProvider soaOperationItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.SoaOperation}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createSoaOperationAdapter() {
        if (soaOperationItemProvider == null) {
            soaOperationItemProvider = new SoaOperationItemProvider(this);
        }

        return soaOperationItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.SoaInputParameter} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected SoaInputParameterItemProvider soaInputParameterItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.SoaInputParameter}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createSoaInputParameterAdapter() {
        if (soaInputParameterItemProvider == null) {
            soaInputParameterItemProvider = new SoaInputParameterItemProvider(this);
        }

        return soaInputParameterItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.SoaService} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected SoaServiceItemProvider soaServiceItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.SoaService}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createSoaServiceAdapter() {
        if (soaServiceItemProvider == null) {
            soaServiceItemProvider = new SoaServiceItemProvider(this);
        }

        return soaServiceItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.RulesItem} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected RulesItemItemProvider rulesItemItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.RulesItem}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createRulesItemAdapter() {
        if (rulesItemItemProvider == null) {
            rulesItemItemProvider = new RulesItemItemProvider(this);
        }

        return rulesItemItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.UserRight} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected UserRightItemProvider userRightItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.UserRight}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createUserRightAdapter() {
        if (userRightItemProvider == null) {
            userRightItemProvider = new UserRightItemProvider(this);
        }

        return userRightItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.RoleRight} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected RoleRightItemProvider roleRightItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.RoleRight}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createRoleRightAdapter() {
        if (roleRightItemProvider == null) {
            roleRightItemProvider = new RoleRightItemProvider(this);
        }

        return roleRightItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.SVGBusinessProcessItem} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected SVGBusinessProcessItemItemProvider svgBusinessProcessItemItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.SVGBusinessProcessItem}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createSVGBusinessProcessItemAdapter() {
        if (svgBusinessProcessItemItemProvider == null) {
            svgBusinessProcessItemItemProvider = new SVGBusinessProcessItemItemProvider(this);
        }

        return svgBusinessProcessItemItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.LinkRulesItem} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected LinkRulesItemItemProvider linkRulesItemItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.LinkRulesItem}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createLinkRulesItemAdapter() {
        if (linkRulesItemItemProvider == null) {
            linkRulesItemItemProvider = new LinkRulesItemItemProvider(this);
        }

        return linkRulesItemItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.ItemRelations} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ItemRelationsItemProvider itemRelationsItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.ItemRelations}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createItemRelationsAdapter() {
        if (itemRelationsItemProvider == null) {
            itemRelationsItemProvider = new ItemRelationsItemProvider(this);
        }

        return itemRelationsItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.ItemRelation} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ItemRelationItemProvider itemRelationItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.ItemRelation}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createItemRelationAdapter() {
        if (itemRelationItemProvider == null) {
            itemRelationItemProvider = new ItemRelationItemProvider(this);
        }

        return itemRelationItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.Notification} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected NotificationItemProvider notificationItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.Notification}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createNotificationAdapter() {
        if (notificationItemProvider == null) {
            notificationItemProvider = new NotificationItemProvider(this);
        }

        return notificationItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.HL7ConnectionItem} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected HL7ConnectionItemItemProvider hl7ConnectionItemItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.HL7ConnectionItem}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createHL7ConnectionItemAdapter() {
        if (hl7ConnectionItemItemProvider == null) {
            hl7ConnectionItemItemProvider = new HL7ConnectionItemItemProvider(this);
        }

        return hl7ConnectionItemItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.UserRoleReference} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected UserRoleReferenceItemProvider userRoleReferenceItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.UserRoleReference}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createUserRoleReferenceAdapter() {
        if (userRoleReferenceItemProvider == null) {
            userRoleReferenceItemProvider = new UserRoleReferenceItemProvider(this);
        }

        return userRoleReferenceItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.HeaderFooterConnectionItem} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected HeaderFooterConnectionItemItemProvider headerFooterConnectionItemItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.HeaderFooterConnectionItem}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createHeaderFooterConnectionItemAdapter() {
        if (headerFooterConnectionItemItemProvider == null) {
            headerFooterConnectionItemItemProvider = new HeaderFooterConnectionItemItemProvider(this);
        }

        return headerFooterConnectionItemItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.FTPConnectionItem} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected FTPConnectionItemItemProvider ftpConnectionItemItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.FTPConnectionItem}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createFTPConnectionItemAdapter() {
        if (ftpConnectionItemItemProvider == null) {
            ftpConnectionItemItemProvider = new FTPConnectionItemItemProvider(this);
        }

        return ftpConnectionItemItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.CustomComponentSetting} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected CustomComponentSettingItemProvider customComponentSettingItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.CustomComponentSetting}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createCustomComponentSettingAdapter() {
        if (customComponentSettingItemProvider == null) {
            customComponentSettingItemProvider = new CustomComponentSettingItemProvider(this);
        }

        return customComponentSettingItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.talend.core.model.properties.TDQItem} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected TDQItemItemProvider tdqItemItemProvider;

    /**
     * This creates an adapter for a {@link org.talend.core.model.properties.TDQItem}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter createTDQItemAdapter() {
        if (tdqItemItemProvider == null) {
            tdqItemItemProvider = new TDQItemItemProvider(this);
        }

        return tdqItemItemProvider;
    }

    /**
     * This returns the root adapter factory that contains this factory.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public ComposeableAdapterFactory getRootAdapterFactory() {
        return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
    }

    /**
     * This sets the composed adapter factory that contains this factory.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
        this.parentAdapterFactory = parentAdapterFactory;
    }

    /**
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public boolean isFactoryForType(Object type) {
        return supportedTypes.contains(type) || super.isFactoryForType(type);
    }

    /**
     * This implementation substitutes the factory itself as the key for the adapter.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Adapter adapt(Notifier notifier, Object type) {
        return super.adapt(notifier, this);
    }

    /**
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public Object adapt(Object object, Object type) {
        if (isFactoryForType(type)) {
            Object adapter = super.adapt(object, type);
            if (!(type instanceof Class) || (((Class)type).isInstance(adapter))) {
                return adapter;
            }
        }

        return null;
    }

    /**
     * This adds a listener.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public void addListener(INotifyChangedListener notifyChangedListener) {
        changeNotifier.addListener(notifyChangedListener);
    }

    /**
     * This removes a listener.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public void removeListener(INotifyChangedListener notifyChangedListener) {
        changeNotifier.removeListener(notifyChangedListener);
    }

    /**
     * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public void fireNotifyChanged(Notification notification) {
        changeNotifier.fireNotifyChanged(notification);

        if (parentAdapterFactory != null) {
            parentAdapterFactory.fireNotifyChanged(notification);
        }
    }

    /**
     * This disposes all of the item providers created by this factory. 
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public void dispose() {
        if (projectItemProvider != null) projectItemProvider.dispose();
        if (projectComponentAuthorisationItemProvider != null) projectComponentAuthorisationItemProvider.dispose();
        if (projectReferenceItemProvider != null) projectReferenceItemProvider.dispose();
        if (statusItemProvider != null) statusItemProvider.dispose();
        if (itemStateItemProvider != null) itemStateItemProvider.dispose();
        if (propertyItemProvider != null) propertyItemProvider.dispose();
        if (linkDocumentationItemItemProvider != null) linkDocumentationItemItemProvider.dispose();
        if (linkTypeItemProvider != null) linkTypeItemProvider.dispose();
        if (businessProcessItemItemProvider != null) businessProcessItemItemProvider.dispose();
        if (byteArrayItemProvider != null) byteArrayItemProvider.dispose();
        if (documentationItemItemProvider != null) documentationItemItemProvider.dispose();
        if (routineItemItemProvider != null) routineItemItemProvider.dispose();
        if (connectionItemItemProvider != null) connectionItemItemProvider.dispose();
        if (snippetVariableItemProvider != null) snippetVariableItemProvider.dispose();
        if (snippetItemItemProvider != null) snippetItemItemProvider.dispose();
        if (delimitedFileConnectionItemItemProvider != null) delimitedFileConnectionItemItemProvider.dispose();
        if (positionalFileConnectionItemItemProvider != null) positionalFileConnectionItemItemProvider.dispose();
        if (regExFileConnectionItemItemProvider != null) regExFileConnectionItemItemProvider.dispose();
        if (csvFileConnectionItemItemProvider != null) csvFileConnectionItemItemProvider.dispose();
        if (databaseConnectionItemItemProvider != null) databaseConnectionItemItemProvider.dispose();
        if (sapConnectionItemItemProvider != null) sapConnectionItemItemProvider.dispose();
        if (xmlFileConnectionItemItemProvider != null) xmlFileConnectionItemItemProvider.dispose();
        if (ldifFileConnectionItemItemProvider != null) ldifFileConnectionItemItemProvider.dispose();
        if (excelFileConnectionItemItemProvider != null) excelFileConnectionItemItemProvider.dispose();
        if (ebcdicConnectionItemItemProvider != null) ebcdicConnectionItemItemProvider.dispose();
        if (mdmConnectionItemItemProvider != null) mdmConnectionItemItemProvider.dispose();
        if (processItemItemProvider != null) processItemItemProvider.dispose();
        if (userRoleItemProvider != null) userRoleItemProvider.dispose();
        if (userItemProvider != null) userItemProvider.dispose();
        if (folderItemItemProvider != null) folderItemItemProvider.dispose();
        if (componentItemProvider != null) componentItemProvider.dispose();
        if (notationHolderItemProvider != null) notationHolderItemProvider.dispose();
        if (userProjectAuthorizationItemProvider != null) userProjectAuthorizationItemProvider.dispose();
        if (contextItemItemProvider != null) contextItemItemProvider.dispose();
        if (spagoBiServerItemProvider != null) spagoBiServerItemProvider.dispose();
        if (licenseItemProvider != null) licenseItemProvider.dispose();
        if (genericSchemaConnectionItemItemProvider != null) genericSchemaConnectionItemItemProvider.dispose();
        if (userModuleAuthorizationItemProvider != null) userModuleAuthorizationItemProvider.dispose();
        if (ldapSchemaConnectionItemItemProvider != null) ldapSchemaConnectionItemItemProvider.dispose();
        if (salesforceSchemaConnectionItemItemProvider != null) salesforceSchemaConnectionItemItemProvider.dispose();
        if (dashboardConnectionItemProvider != null) dashboardConnectionItemProvider.dispose();
        if (executionPlanItemProvider != null) executionPlanItemProvider.dispose();
        if (executionPlanPartItemProvider != null) executionPlanPartItemProvider.dispose();
        if (executionPlanPrmItemProvider != null) executionPlanPrmItemProvider.dispose();
        if (executionPlanPartCmdPrmItemProvider != null) executionPlanPartCmdPrmItemProvider.dispose();
        if (executionPlanPartJobPrmItemProvider != null) executionPlanPartJobPrmItemProvider.dispose();
        if (executionTaskItemProvider != null) executionTaskItemProvider.dispose();
        if (executionTaskCmdPrmItemProvider != null) executionTaskCmdPrmItemProvider.dispose();
        if (executionTaskJobPrmItemProvider != null) executionTaskJobPrmItemProvider.dispose();
        if (taskExecutionHistoryItemProvider != null) taskExecutionHistoryItemProvider.dispose();
        if (planExecutionHistoryItemProvider != null) planExecutionHistoryItemProvider.dispose();
        if (talendTriggerItemProvider != null) talendTriggerItemProvider.dispose();
        if (cronTalendTriggerItemProvider != null) cronTalendTriggerItemProvider.dispose();
        if (cronUITalendTriggerItemProvider != null) cronUITalendTriggerItemProvider.dispose();
        if (simpleTalendTriggerItemProvider != null) simpleTalendTriggerItemProvider.dispose();
        if (fileTriggerItemProvider != null) fileTriggerItemProvider.dispose();
        if (fileTriggerMaskItemProvider != null) fileTriggerMaskItemProvider.dispose();
        if (executionServerItemProvider != null) executionServerItemProvider.dispose();
        if (executionVirtualServerItemProvider != null) executionVirtualServerItemProvider.dispose();
        if (jobletProcessItemItemProvider != null) jobletProcessItemItemProvider.dispose();
        if (jobDocumentationItemItemProvider != null) jobDocumentationItemItemProvider.dispose();
        if (jobletDocumentationItemItemProvider != null) jobletDocumentationItemItemProvider.dispose();
        if (wsdlSchemaConnectionItemItemProvider != null) wsdlSchemaConnectionItemItemProvider.dispose();
        if (schemaInformationItemProvider != null) schemaInformationItemProvider.dispose();
        if (informationItemProvider != null) informationItemProvider.dispose();
        if (sqlPatternItemItemProvider != null) sqlPatternItemItemProvider.dispose();
        if (componentSettingItemProvider != null) componentSettingItemProvider.dispose();
        if (statAndLogsSettingsItemProvider != null) statAndLogsSettingsItemProvider.dispose();
        if (implicitContextSettingsItemProvider != null) implicitContextSettingsItemProvider.dispose();
        if (soaOperationItemProvider != null) soaOperationItemProvider.dispose();
        if (soaInputParameterItemProvider != null) soaInputParameterItemProvider.dispose();
        if (soaServiceItemProvider != null) soaServiceItemProvider.dispose();
        if (rulesItemItemProvider != null) rulesItemItemProvider.dispose();
        if (userRightItemProvider != null) userRightItemProvider.dispose();
        if (roleRightItemProvider != null) roleRightItemProvider.dispose();
        if (svgBusinessProcessItemItemProvider != null) svgBusinessProcessItemItemProvider.dispose();
        if (linkRulesItemItemProvider != null) linkRulesItemItemProvider.dispose();
        if (itemRelationsItemProvider != null) itemRelationsItemProvider.dispose();
        if (itemRelationItemProvider != null) itemRelationItemProvider.dispose();
        if (notificationItemProvider != null) notificationItemProvider.dispose();
        if (hl7ConnectionItemItemProvider != null) hl7ConnectionItemItemProvider.dispose();
        if (userRoleReferenceItemProvider != null) userRoleReferenceItemProvider.dispose();
        if (headerFooterConnectionItemItemProvider != null) headerFooterConnectionItemItemProvider.dispose();
        if (ftpConnectionItemItemProvider != null) ftpConnectionItemItemProvider.dispose();
        if (customComponentSettingItemProvider != null) customComponentSettingItemProvider.dispose();
        if (tdqItemItemProvider != null) tdqItemItemProvider.dispose();
    }

}
