/**
 *
 * $Id$
 */
package org.talend.designer.core.model.utils.emf.talendfile.validation;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link org.talend.designer.core.model.utils.emf.talendfile.MetadataType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MetadataTypeValidator {
    boolean validate();

    boolean validateColumn(EList value);
    boolean validateComment(String value);
    boolean validateConnector(String value);
    boolean validateLabel(String value);
    boolean validateName(String value);
    boolean validateSource(String value);
    boolean validateType(String value);
}
