/**
 *
 * $Id$
 */
package org.talend.designer.core.model.utils.emf.talendfile.validation;

import org.eclipse.emf.common.util.EList;

import org.talend.designer.core.model.utils.emf.talendfile.AbstractExternalData;
import org.talend.designer.core.model.utils.emf.talendfile.NodeContainerType;

/**
 * A sample validator interface for {@link org.talend.designer.core.model.utils.emf.talendfile.NodeType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NodeTypeValidator {
    boolean validate();

    boolean validateElementParameter(EList value);
    boolean validateMetadata(EList value);
    boolean validateBinaryData(byte[] value);
    boolean validateStringData(String value);
    boolean validateComponentName(String value);
    boolean validateComponentVersion(String value);
    boolean validateOffsetLabelX(int value);
    boolean validateOffsetLabelY(int value);
    boolean validatePosX(int value);
    boolean validatePosY(int value);
    boolean validateSizeX(int value);
    boolean validateSizeY(int value);
    boolean validateScreenshot(byte[] value);
    boolean validateNodeData(AbstractExternalData value);
    boolean validateNodeContainer(NodeContainerType value);
}
