// ============================================================================
//
// Copyright (C) 2006-2010 Talend Inc. - www.talend.com
//
// This source code is available under agreement available at
// %InstallDIR%\features\org.talend.rcp.branding.%PRODUCTNAME%\%PRODUCTNAME%license.txt
//
// You should have received a copy of the agreement
// along with this program; if not, write to Talend SA
// 9 rue Pages 92150 Suresnes, France
//
// ============================================================================
package org.talend.core.ui.branding;

/**
 * wzhang class global comment. Detailled comment
 */
public class BrandingConstants {

    public static final String LICENSE_LINE = "// ============================================================================";

    public static final String GENERATEDCODE_COPYRIGHT_TITLE = "Copyright (c) 2005-2010, Talend Inc.";

    public static final String GENERATEDCODE_COPYRIGHT_BODY1 = "This source code has been automatically generated by";

    public static final String GENERATEDCODE_COPYRIGHT_BODY2 = "/ JobDesigner (CodeGenerator version";

    public static final String GENERATEDCODE_COPYRIGHT_BODY3 = "You can find more information about Talend products at www.talend.com.";

    public static final String GENERATEDCODE_COPYRIGHT_BODY4 = "You may distribute this code under the terms of the GNU LGPL license";

    public static final String GENERATEDCODE_COPYRIGHT_BODY5 = "(http://www.gnu.org/licenses/lgpl.html).";
}
