/**
 *
 * $Id$
 */
package org.talend.designer.core.model.utils.emf.component.validation;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link org.talend.designer.core.model.utils.emf.component.IMPORTType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface IMPORTTypeValidator {
    boolean validate();

    boolean validateINSTALL(EList value);
    boolean validateURL(EList value);
    boolean validateBundleID(String value);
    boolean validateMESSAGE(String value);
    boolean validateMODULE(String value);
    boolean validateMODULEGROUP(String value);
    boolean validateMRREQUIRED(boolean value);
    boolean validateNAME(String value);
    boolean validateREQUIRED(boolean value);
    boolean validateREQUIREDIF(String value);
    boolean validateSHOW(boolean value);
    boolean validateUrlPath(String value);
    boolean validateMVN(String value);
}
